export const site = {
  name: "The Get Set Go Holidays",
  shortName: "Get Set Go Holidays",
  tagline: "Explore the World with Ease & Comfort",
  description:
    "We turn your travel dreams into reality with personalised tour packages, hotel bookings, taxi services, flights and complete trip planning.",
  phone: "+918796042440",
  whatsapp: "+918796042440",
  email: "info@thegetsetgoholidays.com",
  email2: "thegetsetgoholidays@gmail.com",
  address:
    "1138, 11th Floor, Gaur City Mall, Greater Noida West, Uttar Pradesh 201318",
  hours: "Monday to Sunday 10am — 8:30pm",
  social: {
    facebook: "https://www.facebook.com/profile.php?id=61579521610645",
    instagram: "https://www.instagram.com/thegetsetgo.holidays/",
    linkedin: "https://www.linkedin.com/in/the-get-set-go-holidays-428a413b8/",
    x: "https://x.com/thegetsetgo",
    youtube: "https://www.youtube.com/@getsetgoholidays",
    whatsapp: "https://wa.me/918796042440",
  },
};

export const nav = [
  { label: "Home", href: "/" },
  { label: "About Us", href: "/about" },
  {
    label: "Destinations",
    href: "/destinations",
    children: [
      { label: "International", href: "/destinations?type=international" },
      { label: "Domestic", href: "/destinations?type=domestic" },
    ],
  },
  { label: "Packages", href: "/packages" },
  { label: "Services", href: "/services" },
  { label: "Testimonials", href: "/testimonials" },
  { label: "Blog", href: "/blog" },
  { label: "Contact", href: "/contact" },
];

export const services = [
  {
    title: "Customized Tour Packages",
    icon: "map",
    description:
      "Tailor-made domestic and international holiday packages crafted around your budget, interests and travel dates.",
  },
  {
    title: "Hotel Booking",
    icon: "bed",
    description:
      "Hand-picked stays from budget hotels to luxury resorts, secured at the best available rates.",
  },
  {
    title: "Taxi & Cab Services",
    icon: "car",
    description:
      "Reliable, sanitized cabs with professional drivers for sightseeing, transfers and outstation trips.",
  },
  {
    title: "Flight Booking",
    icon: "ticket",
    description:
      "Competitive air fares across domestic and international routes with complete ticketing support.",
  },
  {
    title: "Complete Tour Planning",
    icon: "clipboard",
    description:
      "End-to-end itinerary design, bookings and on-trip assistance for a completely hassle-free experience.",
  },
  {
    title: "Passport / Visa Services",
    icon: "passport",
    description:
      "Step-by-step guidance and documentation support for passports and tourist visas worldwide.",
  },
  {
    title: "Honeymoon & Group Tours",
    icon: "heart",
    description:
      "Romantic honeymoon escapes and well-organised group, rider and corporate travel experiences.",
  },
  {
    title: "Corporate Tours",
    icon: "briefcase",
    description:
      "Professional corporate travel, MICE and team outings with seamless logistics, stays and conference arrangements.",
  },
];

export const destinations = [
  // ---------------- International ----------------
  {
    slug: "abu-dhabi",
    name: "Abu Dhabi",
    country: "UAE",
    region: "international",
    tagline: "Ultra-modern architecture, cultural treasures and Arabian luxury.",
    image: "/abu-dhabi/1.jpg",
    bestTime: "November to March",
    duration: "4 Nights / 5 Days",
    price: "From ₹60,000 per person",
    summary:
      "Abu Dhabi, the capital of the UAE, blends futuristic skyscrapers with rich Emirati heritage. Home to the stunning Sheikh Zayed Grand Mosque, Ferrari World and the cultural district of Saadiyat Island, it offers world-class attractions, pristine beaches and desert adventures.",
    highlights: [
      "Sheikh Zayed Grand Mosque",
      "Ferrari World & Yas Island",
      "Louvre Abu Dhabi museum",
      "Desert safari and dune bashing",
      "Corniche waterfront stroll",
    ],
    gallery: [
      "/abu-dhabi/1.jpg", "/abu-dhabi/2.jpg", "/abu-dhabi/3.jpg",
      "/abu-dhabi/4.jpg", "/abu-dhabi/5.jpg", "/abu-dhabi/6.jpg",
      "/abu-dhabi/7.jpg", "/abu-dhabi/8.jpg", "/abu-dhabi/9.jpg",
      "/abu-dhabi/10.jpg", "/abu-dhabi/11.jpg", "/abu-dhabi/12.jpg",
    ],
  },
  {
    slug: "bali",
    name: "Bali",
    country: "Indonesia",
    region: "international",
    tagline: "Discover Bali's beautiful beaches, peaceful temples & unforgettable experiences.",
    image: "/bali/1.jpg",
    bestTime: "April to October",
    duration: "5 Nights / 6 Days",
    price: "From ₹45,000 per person",
    summary:
      "Bali blends golden beaches, lush rice terraces and a deeply spiritual culture. From the cliffs of Uluwatu to the art villages of Ubud, every corner feels like a postcard.",
    highlights: [
      "Uluwatu Temple & Kecak Fire Dance at sunset",
      "Ubud rice terraces and sacred monkey forest",
      "Seminyak beach clubs and Canggu surf spots",
      "Nusa Penida island day cruise",
      "Balinese spa and authentic local cuisine",
    ],
    gallery: [
      "/bali/1.jpg", "/bali/2.jpg", "/bali/3.jpg",
      "/bali/4.jpg", "/bali/5.jpg", "/bali/6.jpg",
      "/bali/7.jpg", "/bali/8.jpg", "/bali/9.jpg",
      "/bali/10.jpg", "/bali/11.jpg", "/bali/12.jpg",
      "/bali/13.jpg", "/bali/14.jpg", "/bali/15.jpg",
    ],
  },
  {
    slug: "bangkok-pattaya",
    name: "Bangkok & Pattaya",
    country: "Thailand",
    region: "international",
    tagline: "Bangkok's vibrant energy meets Pattaya's stunning beaches.",
    image: "/bangkok-pattya/1.jpg",
    bestTime: "November to April",
    duration: "5 Nights / 6 Days",
    price: "From ₹35,000 per person",
    summary:
      "Bangkok & Pattaya offer the perfect Thai combo — Bangkok's golden temples, floating markets and rooftop bars paired with Pattaya's gorgeous beaches, water sports and vibrant nightlife. A complete Thailand experience in one trip.",
    highlights: [
      "Grand Palace & Wat Phra Kaew",
      "Floating market tour",
      "Pattaya beach and water sports",
      "Coral Island snorkelling",
      "Sanctuary of Truth & Alcazar Show",
    ],
    gallery: [
      "/bangkok-pattya/1.jpg", "/bangkok-pattya/2.jpg", "/bangkok-pattya/3.jpg",
      "/bangkok-pattya/4.jpg", "/bangkok-pattya/5.jpg", "/bangkok-pattya/6.jpg",
      "/bangkok-pattya/7.jpg", "/bangkok-pattya/8.jpg", "/bangkok-pattya/9.jpg",
      "/bangkok-pattya/10.jpg",
    ],
  },
  {
    slug: "bhutan",
    name: "Bhutan",
    country: "Bhutan",
    region: "international",
    tagline: "The Land of the Thunder Dragon — happiness is a place.",
    image: "/bhutan/1.jpg",
    bestTime: "March to May & September to November",
    duration: "5 Nights / 6 Days",
    price: "From ₹55,000 per person",
    summary:
      "Bhutan is a Himalayan kingdom like no other, measuring progress by Gross National Happiness. From the cliffside Tiger's Nest Monastery to pristine valleys and ancient dzongs, it offers a deeply spiritual and unspoiled travel experience.",
    highlights: [
      "Tiger's Nest Monastery (Paro Taktsang)",
      "Punakha Dzong and suspension bridge",
      "Thimphu's Buddha Dordenma statue",
      "Traditional Bhutanese festival",
      "Scenic drives through Himalayan valleys",
    ],
    gallery: [
      "/bhutan/1.jpg", "/bhutan/2.jpg", "/bhutan/3.jpg",
      "/bhutan/4.jpg", "/bhutan/5.jpg", "/bhutan/6.jpg",
      "/bhutan/7.jpg", "/bhutan/8.jpg", "/bhutan/9.jpg",
      "/bhutan/10.jpg", "/bhutan/11.jpg", "/bhutan/12.jpg",
    ],
  },
  {
    slug: "canada",
    name: "Canada",
    country: "Canada",
    region: "international",
    tagline: "Majestic landscapes, vibrant cities and endless adventures.",
    image: "/canada/1.jpg",
    bestTime: "May to October",
    duration: "8 Nights / 9 Days",
    price: "From ₹1,50,000 per person",
    summary:
      "Canada is a land of dramatic natural beauty — from the Rocky Mountains and turquoise lakes of Banff to the multicultural buzz of Toronto and Vancouver. Experience Niagara Falls, spot wildlife and explore pristine national parks.",
    highlights: [
      "Niagara Falls boat cruise",
      "Banff National Park & Lake Louise",
      "CN Tower and Toronto skyline",
      "Stanley Park and Vancouver harbour",
      "Whistler mountain adventure",
    ],
    gallery: [
      "/canada/1.jpg", "/canada/2.jpg", "/canada/3.jpg",
      "/canada/4.jpg", "/canada/5.jpg", "/canada/6.jpg",
      "/canada/7.jpg", "/canada/8.jpg", "/canada/9.jpg",
      "/canada/10.jpg", "/canada/11.jpg", "/canada/12.jpg",
    ],
  },
  {
    slug: "dubai",
    name: "Dubai",
    country: "UAE",
    region: "international",
    tagline: "Experience luxury, adventure, and world-class attractions.",
    image: "/dubai/1.jpg",
    bestTime: "November to March",
    duration: "4 Nights / 5 Days",
    price: "From ₹55,000 per person",
    summary:
      "Dubai is a city of superlatives — towering skylines, desert safaris and futuristic attractions. From the Burj Khalifa to dune bashing, it delivers luxury at every turn.",
    highlights: [
      "Burj Khalifa & Dubai Mall fountain show",
      "Desert safari with BBQ dinner",
      "Marina cruise and Palm Jumeirah",
      "Global Village and theme parks",
      "Gold & spice souks",
    ],
    gallery: [
      "/dubai/1.jpg", "/dubai/2.jpg", "/dubai/3.jpg",
      "/dubai/4.jpg", "/dubai/5.jpg", "/dubai/6.jpg",
      "/dubai/7.jpg", "/dubai/8.jpg", "/dubai/9.jpg",
      "/dubai/10.jpg", "/dubai/11.jpg", "/dubai/12.jpg",
      "/dubai/13.jpg", "/dubai/14.jpg",
    ],
  },
  {
    slug: "kazakhstan",
    name: "Kazakhstan",
    country: "Kazakhstan",
    region: "international",
    tagline: "Vast steppes, futuristic cities and ancient Silk Road charm.",
    image: "/kazakhstan/1.jpg",
    bestTime: "April to October",
    duration: "6 Nights / 7 Days",
    price: "From ₹65,000 per person",
    summary:
      "Kazakhstan, the world's ninth-largest country, offers a unique blend of ultra-modern Astana, historic Almaty and the vast, untouched steppes of Central Asia. Explore canyons, ski resorts and Silk Road heritage.",
    highlights: [
      "Astana's futuristic architecture",
      "Almaty's Green Bazaar and Zenkov Cathedral",
      "Charyn Canyon — Grand Canyon's little brother",
      "Medeu ice skating rink and ski resort",
      "Kolsai Lakes horseback trekking",
    ],
    gallery: [
      "/kazakhstan/1.jpg", "/kazakhstan/2.jpg", "/kazakhstan/3.jpg",
      "/kazakhstan/4.jpg", "/kazakhstan/5.jpg", "/kazakhstan/6.jpg",
      "/kazakhstan/7.jpg", "/kazakhstan/8.jpg", "/kazakhstan/9.jpg",
      "/kazakhstan/10.jpg",
    ],
  },
  {
    slug: "laos",
    name: "Laos",
    country: "Laos",
    region: "international",
    tagline: "Timeless temples, tranquil rivers and Southeast Asian serenity.",
    image: "/laos/1.jpg",
    bestTime: "November to March",
    duration: "5 Nights / 6 Days",
    price: "From ₹50,000 per person",
    summary:
      "Laos is Southeast Asia's most laid-back destination. Luang Prabang's golden temples, Vientiane's riverside charm and the slow pace of the Mekong make it perfect for travellers seeking genuine tranquillity and unspoiled culture.",
    highlights: [
      "Luang Prabang's night market and temples",
      "Kuang Si Waterfalls turquoise pools",
      "Mekong River sunset cruise",
      "Vientiane's Pha That Luang stupa",
      "Elephant sanctuary experience",
    ],
    gallery: [
      "/laos/1.jpg", "/laos/2.jpg", "/laos/3.jpg",
      "/laos/4.jpg", "/laos/5.jpg", "/laos/6.jpg",
      "/laos/7.jpg", "/laos/8.jpg", "/laos/9.jpg",
      "/laos/10.jpg", "/laos/11.jpg",
    ],
  },
  {
    slug: "london",
    name: "London",
    country: "United Kingdom",
    region: "international",
    tagline: "Royal heritage, iconic landmarks and world-class culture.",
    image: "/london/1.jpg",
    bestTime: "March to May & September to November",
    duration: "6 Nights / 7 Days",
    price: "From ₹1,20,000 per person",
    summary:
      "London is a city where centuries of history meet cutting-edge culture. From the Tower of London and Buckingham Palace to the West End and Camden Market, every neighbourhood tells a story.",
    highlights: [
      "Buckingham Palace and Changing of the Guard",
      "London Eye and Houses of Parliament",
      "Tower of London and Tower Bridge",
      "British Museum and Natural History Museum",
      "West End theatre and Covent Garden",
    ],
    gallery: [
      "/london/1.jpg", "/london/2.jpg", "/london/3.jpg",
      "/london/4.jpg", "/london/5.jpg", "/london/6.jpg",
      "/london/7.jpg", "/london/8.jpg", "/london/9.jpg",
      "/london/10.jpg", "/london/11.jpg",
    ],
  },
  {
    slug: "malaysia",
    name: "Malaysia",
    country: "Malaysia",
    region: "international",
    tagline: "Kuala Lumpur's skyline meets Langkawi's tropical shores.",
    image: "/malaysia/1.jpg",
    bestTime: "December to August",
    duration: "5 Nights / 6 Days",
    price: "From ₹40,000 per person",
    summary:
      "Malaysia is a vibrant tapestry of Malay, Chinese and Indian cultures. Explore the iconic Petronas Towers in Kuala Lumpur, relax on Langkawi's pristine beaches and trek through Borneo's ancient rainforests.",
    highlights: [
      "Petronas Towers and KLCC",
      "Langkawi cable car and sky bridge",
      "Batu Caves and Chinatown",
      "Cameron Highlands tea plantations",
      "Borneo orangutan sanctuary",
    ],
    gallery: [
      "/malaysia/1.jpg", "/malaysia/2.jpg", "/malaysia/3.jpg",
      "/malaysia/4.jpg", "/malaysia/5.jpg", "/malaysia/6.jpg",
      "/malaysia/7.jpg", "/malaysia/8.jpg", "/malaysia/9.jpg",
      "/malaysia/10.jpg",
    ],
  },
  {
    slug: "maldives",
    name: "Maldives",
    country: "Maldives",
    region: "international",
    tagline: "Overwater villas and crystal-clear lagoons.",
    image: "/maldives/1.jpg",
    bestTime: "November to April",
    duration: "4 Nights / 5 Days",
    price: "From ₹75,000 per person",
    summary:
      "The Maldives is the ultimate island escape — overwater villas, house reefs and endless turquoise horizons. Perfect for honeymoons and slow, sunny getaways.",
    highlights: [
      "Overwater villa stay",
      "Snorkelling & dolphin watching",
      "Sandbank picnics",
      "Sunset candle-light dinners",
      "Water sports and spas",
    ],
    gallery: [
      "/maldives/1.jpg", "/maldives/2.jpg", "/maldives/3.jpg",
      "/maldives/4.jpg", "/maldives/5.jpg", "/maldives/6.jpg",
      "/maldives/7.jpg", "/maldives/8.jpg", "/maldives/9.jpg",
      "/maldives/10.jpg", "/maldives/11.jpg", "/maldives/12.jpg",
      "/maldives/13.jpg",
    ],
  },
  {
    slug: "mauritius",
    name: "Mauritius",
    country: "Mauritius",
    region: "international",
    tagline: "Tropical paradise with turquoise lagoons and cultural fusion.",
    image: "/mauritius/1.jpg",
    bestTime: "May to December",
    duration: "5 Nights / 6 Days",
    price: "From ₹80,000 per person",
    summary:
      "Mauritius is a dream island destination — powdery white beaches, coral reefs and lush sugarcane fields. Beyond the beaches, discover Creole culture, colonial history and adventure sports in this Indian Ocean gem.",
    highlights: [
      "Île aux Cerfs island and beach",
      "Chamarel Seven Coloured Earth",
      "Underwater waterfall illusion",
      "Port Louis market and Caudan Waterfront",
      "Black River Gorges National Park",
    ],
    gallery: [
      "/mauritius/1.jpg", "/mauritius/2.jpg", "/mauritius/3.jpg",
      "/mauritius/4.jpg", "/mauritius/5.jpg", "/mauritius/6.jpg",
      "/mauritius/7.jpg", "/mauritius/8.jpg", "/mauritius/9.jpg",
      "/mauritius/10.jpg",
    ],
  },
  {
    slug: "paris",
    name: "Paris",
    country: "France",
    region: "international",
    tagline: "Stunning views and romantic vibes at the iconic Eiffel Tower.",
    image: "/paris/1.jpg",
    bestTime: "April to June",
    duration: "6 Nights / 7 Days",
    price: "From ₹95,000 per person",
    summary:
      "Paris is the city of love, art and timeless architecture. Stroll the Seine, gaze at the Eiffel Tower and explore world-class museums, cafés and boulevards.",
    highlights: [
      "Eiffel Tower and Seine river cruise",
      "Louvre Museum and Notre-Dame",
      "Versailles Palace day trip",
      "Montmartre & Champs-Élysées",
      "Disneyland Paris option",
    ],
    gallery: [
      "/paris/1.jpg", "/paris/2.jpg", "/paris/3.jpg",
      "/paris/4.jpg", "/paris/5.jpg", "/paris/6.jpg",
      "/paris/7.jpg", "/paris/8.jpg", "/paris/9.jpg",
      "/paris/10.jpg", "/paris/11.jpg",
    ],
  },
  {
    slug: "philippines",
    name: "Philippines",
    country: "Philippines",
    region: "international",
    tagline: "7,000 islands of pristine beaches, lagoons and warm smiles.",
    image: "/philippines/1.jpg",
    bestTime: "November to May",
    duration: "6 Nights / 7 Days",
    price: "From ₹55,000 per person",
    summary:
      "The Philippines is an archipelago of stunning diversity — from the limestone cliffs and emerald lagoons of Palawan to the chocolate hills of Bohol and the vibrant streets of Manila. A paradise for beach lovers and adventurers.",
    highlights: [
      "Palawan's Underground River and El Nido",
      "Chocolate Hills and tarsier sanctuary",
      "Boracay's White Beach",
      "Cebu whale shark snorkelling",
      "Manila Intramuros and cultural tour",
    ],
    gallery: [
      "/philippines/1.jpg", "/philippines/2.jpg", "/philippines/3.jpg",
      "/philippines/4.jpg", "/philippines/5.jpg", "/philippines/6.jpg",
      "/philippines/7.jpg", "/philippines/8.jpg", "/philippines/9.jpg",
      "/philippines/10.jpg",
    ],
  },
  {
    slug: "phuket-krabi",
    name: "Phuket & Krabi",
    country: "Thailand",
    region: "international",
    tagline: "Thailand's ultimate beach duo — vibrant Phuket, serene Krabi.",
    image: "/phuket-krabi/1.jpg",
    bestTime: "November to April",
    duration: "6 Nights / 7 Days",
    price: "From ₹42,000 per person",
    summary:
      "Phuket & Krabi together offer the best of Thailand's Andaman coast — Phuket's lively beaches, nightlife and culture paired with Krabi's dramatic limestone cliffs, Railay Beach and Phi Phi Island paradise.",
    highlights: [
      "Phi Phi Island day tour",
      "Railay Beach rock climbing",
      "James Bond Island and Hong Lagoon",
      "Patong beach and Bangla Road",
      "Emerald Pool and hot springs",
    ],
    gallery: [
      "/phuket-krabi/1.jpg", "/phuket-krabi/2.jpg", "/phuket-krabi/3.jpg",
      "/phuket-krabi/4.jpg", "/phuket-krabi/5.jpg", "/phuket-krabi/6.jpg",
      "/phuket-krabi/7.jpg", "/phuket-krabi/8.jpg", "/phuket-krabi/9.jpg",
      "/phuket-krabi/10.jpg",
    ],
  },
  {
    slug: "sri-lanka",
    name: "Sri Lanka",
    country: "Sri Lanka",
    region: "international",
    tagline: "Tea gardens, ancient ruins and tropical beaches await.",
    image: "/srilanka/1.jpg",
    bestTime: "December to March",
    duration: "6 Nights / 7 Days",
    price: "From ₹38,000 per person",
    summary:
      "Sri Lanka is a teardrop-shaped island of wonders — ancient Buddhist ruins in Anuradhapura, tea plantations in Nuwara Eliya, safari in Yala National Park and golden beaches in Bentota. A complete island experience.",
    highlights: [
      "Sigiriya Rock Fortress",
      "Temple of the Tooth in Kandy",
      "Nuwara Eliya tea plantation tour",
      "Yala National Park safari",
      "Bentota beach and water sports",
    ],
    gallery: [
      "/srilanka/1.jpg", "/srilanka/2.jpg", "/srilanka/3.jpg",
      "/srilanka/4.jpg", "/srilanka/5.jpg", "/srilanka/6.jpg",
      "/srilanka/7.jpg", "/srilanka/8.jpg", "/srilanka/9.jpg",
      "/srilanka/10.jpg",
    ],
  },
  {
    slug: "switzerland",
    name: "Switzerland",
    country: "Switzerland",
    region: "international",
    tagline: "Snow peaks, scenic railways and storybook villages.",
    image: "/switzerland/1.jpg",
    bestTime: "May to September",
    duration: "7 Nights / 8 Days",
    price: "From ₹1,20,000 per person",
    summary:
      "Switzerland is a paradise of alpine lakes, glaciers and charming towns. Ride panoramic trains, visit Interlaken and Zermatt, and breathe in the crisp mountain air.",
    highlights: [
      "Interlaken adventure sports",
      "Jungfraujoch — Top of Europe",
      "Scenic Glacier Express railway",
      "Lake Geneva and Lucerne",
      "Zermatt & the Matterhorn",
    ],
    gallery: [
      "/switzerland/1.jpg", "/switzerland/2.jpg", "/switzerland/3.jpg",
      "/switzerland/4.jpg", "/switzerland/5.jpg", "/switzerland/6.jpg",
      "/switzerland/7.jpg", "/switzerland/8.jpg", "/switzerland/9.jpg",
      "/switzerland/10.jpg",
    ],
  },
  {
    slug: "vietnam",
    name: "Vietnam",
    country: "Vietnam",
    region: "international",
    tagline: "Limestone bays, lantern towns and rich street food.",
    image: "/vietnam/1.jpg",
    bestTime: "February to April & August to October",
    duration: "6 Nights / 7 Days",
    price: "From ₹65,000 per person",
    summary:
      "Vietnam blends emerald Halong Bay, the lantern-lit streets of Hoi An and the buzzing energy of Hanoi and Ho Chi Minh City. A feast of culture, cuisine and scenery.",
    highlights: [
      "Halong Bay cruise",
      "Hoi An ancient town",
      "Hanoi Old Quarter",
      "Cu Chi tunnels",
      "Street food trails",
    ],
    gallery: [
      "/vietnam/1.jpg", "/vietnam/2.jpg", "/vietnam/3.jpg",
      "/vietnam/4.jpg", "/vietnam/5.jpg", "/vietnam/6.jpg",
      "/vietnam/7.jpg", "/vietnam/8.jpg", "/vietnam/9.jpg",
      "/vietnam/10.jpg", "/vietnam/11.jpg", "/vietnam/12.jpg",
    ],
  },
  // ---------------- Domestic ----------------
  {
    slug: "andhra-pradesh",
    name: "Andhra Pradesh",
    country: "Andhra Pradesh, India",
    region: "domestic",
    tagline: "Land of sacred temples, rich heritage and coastal beauty.",
    image: "/andhra-pradesh/ahobilam/1.jpg",
    bestTime: "October to March",
    duration: "5 Nights / 6 Days",
    price: "From ₹12,000 per person",
    summary:
      "Andhra Pradesh is a land of divine temples, ancient history and stunning coastline. From the legendary Ahobilam with its nine Narasimha temples, the sacred Sri Kalahasti temple known as the Kailash of the South, to the world-famous Tirupati Balaji Temple atop the Tirumala hills — this is a spiritual journey like no other.",
    highlights: [
      "Tirupati Balaji Darshan at Tirumala",
      "Ahobilam's nine Narasimha temples",
      "Sri Kalahasti Rahu-Ketu pooja",
      "Lepakshi Veerabhadra Temple and hanging pillar",
      "Araku Valley scenic train ride",
      "Visakhapatnam beaches and Borra Caves",
    ],
    gallery: [
      "/andhra-pradesh/ahobilam/1.jpg",
      "/andhra-pradesh/ahobilam/2.jpg",
      "/andhra-pradesh/ahobilam/3.jpg",
      "/andhra-pradesh/ahobilam/4.jpg",
      "/andhra-pradesh/ahobilam/5.jpg",
      "/andhra-pradesh/ahobilam/6.jpg",
      "/andhra-pradesh/ahobilam/7.jpg",
      "/andhra-pradesh/ahobilam/8.jpg",
      "/andhra-pradesh/ahobilam/9.jpg",
      "/andhra-pradesh/ahobilam/10.jpg",
      "/andhra-pradesh/ahobilam/11.jpg",
      "/andhra-pradesh/ahobilam/12.jpg",
      "/andhra-pradesh/srikalahasti/1.jpg",
      "/andhra-pradesh/srikalahasti/2.jpg",
      "/andhra-pradesh/srikalahasti/3.jpg",
      "/andhra-pradesh/srikalahasti/4.jpg",
      "/andhra-pradesh/srikalahasti/5.jpg",
      "/andhra-pradesh/srikalahasti/6.jpg",
      "/andhra-pradesh/srikalahasti/7.jpg",
      "/andhra-pradesh/srikalahasti/8.jpg",
      "/andhra-pradesh/srikalahasti/9.jpg",
      "/andhra-pradesh/srikalahasti/10.jpg",
      "/andhra-pradesh/tripati-trimula/1.jpg",
      "/andhra-pradesh/tripati-trimula/2.jpg",
      "/andhra-pradesh/tripati-trimula/3.jpg",
      "/andhra-pradesh/tripati-trimula/4.jpg",
      "/andhra-pradesh/tripati-trimula/5.jpg",
      "/andhra-pradesh/tripati-trimula/6.jpg",
      "/andhra-pradesh/tripati-trimula/7.jpg",
      "/andhra-pradesh/tripati-trimula/8.jpg",
      "/andhra-pradesh/tripati-trimula/9.jpg",
      "/andhra-pradesh/tripati-trimula/10.jpg",
    ],
    subDestinations: [
      {
        slug: "ahobilam",
        name: "Ahobilam",
        tagline: "The sacred abode of Lord Narasimha — nine temples in a scenic hill setting.",
        image: "/andhra-pradesh/ahobilam/1.jpg",
        highlights: [
          "Nine Narasimha temples (Nava Narasimhas)",
          "Upper and Lower Ahobilam temple complex",
          "Scenic hill trek between temples",
          "Bhargava, Yogananda, and Lakshmi Narasimha",
          "Annual Brahmotsavam festival",
        ],
        gallery: [
          "/andhra-pradesh/ahobilam/1.jpg", "/andhra-pradesh/ahobilam/2.jpg",
          "/andhra-pradesh/ahobilam/3.jpg", "/andhra-pradesh/ahobilam/4.jpg",
          "/andhra-pradesh/ahobilam/5.jpg", "/andhra-pradesh/ahobilam/6.jpg",
          "/andhra-pradesh/ahobilam/7.jpg", "/andhra-pradesh/ahobilam/8.jpg",
          "/andhra-pradesh/ahobilam/9.jpg", "/andhra-pradesh/ahobilam/10.jpg",
          "/andhra-pradesh/ahobilam/11.jpg", "/andhra-pradesh/ahobilam/12.jpg",
        ],
      },
      {
        slug: "srikalahasti",
        name: "Srikalahasti",
        tagline: "The Kailash of the South — famous for Rahu-Ketu pooja and the Shiva temple.",
        image: "/andhra-pradesh/srikalahasti/1.jpg",
        highlights: [
          "Sri Kalahasteeswara Temple — ancient Shiva shrine",
          "Rahu-Ketu pooja for astrological remedies",
          "Pancha Bhoota Sthalam — Vayu (wind) linga",
          "Hanging pillar and sculptural marvels",
          "Kalahasti temple car festival",
        ],
        gallery: [
          "/andhra-pradesh/srikalahasti/1.jpg", "/andhra-pradesh/srikalahasti/2.jpg",
          "/andhra-pradesh/srikalahasti/3.jpg", "/andhra-pradesh/srikalahasti/4.jpg",
          "/andhra-pradesh/srikalahasti/5.jpg", "/andhra-pradesh/srikalahasti/6.jpg",
          "/andhra-pradesh/srikalahasti/7.jpg", "/andhra-pradesh/srikalahasti/8.jpg",
          "/andhra-pradesh/srikalahasti/9.jpg", "/andhra-pradesh/srikalahasti/10.jpg",
        ],
      },
      {
        slug: "tirupati",
        name: "Tirupati",
        tagline: "The world-famous Tirumala Venkateswara Temple — the richest and holiest shrine.",
        image: "/andhra-pradesh/tripati-trimula/1.jpg",
        highlights: [
          "Tirumala Venkateswara Temple darshan",
          "Sri Padmavathi Devi Temple in Tiruchanur",
          "Talakona waterfalls and nature trail",
          "Chandragiri Fort and museum",
          "Kapila Theertham waterfall temple",
        ],
        gallery: [
          "/andhra-pradesh/tripati-trimula/1.jpg", "/andhra-pradesh/tripati-trimula/2.jpg",
          "/andhra-pradesh/tripati-trimula/3.jpg", "/andhra-pradesh/tripati-trimula/4.jpg",
          "/andhra-pradesh/tripati-trimula/5.jpg", "/andhra-pradesh/tripati-trimula/6.jpg",
          "/andhra-pradesh/tripati-trimula/7.jpg", "/andhra-pradesh/tripati-trimula/8.jpg",
          "/andhra-pradesh/tripati-trimula/9.jpg", "/andhra-pradesh/tripati-trimula/10.jpg",
        ],
      },
    ],
  },
  {
    slug: "shimla",
    name: "Shimla",
    country: "Himachal Pradesh, India",
    region: "domestic",
    tagline: "The Queen of Hills and her colonial charm.",
    image: "/uploads/2026/04/shimla.jpg",
    bestTime: "March to June & Dec-Jan",
    duration: "3 Nights / 4 Days",
    price: "From ₹12,000 per person",
    summary:
      "Shimla's pine-covered ridges, toy train and Mall Road capture the romance of the Himalayas. A classic hill-station retreat for families and couples alike.",
    highlights: [
      "Mall Road and Ridge",
      "Kufri adventure point",
      "Jakhoo Temple",
      "Heritage toy train ride",
      "Scenic ridge walks",
    ],
    gallery: [
      "/shimla/1.jpg",
      "/shimla/2.jpg",
      "/shimla/3.jpg",
      "/shimla/4.jpg",
      "/shimla/5.jpg",
      "/shimla/6.jpg",
      "/shimla/7.jpg",
      "/shimla/8.jpg",
      "/shimla/9.jpg",
      "/shimla/10.jpg",
      "/shimla/11.jpg",
    ],
  },
  {
    slug: "manali",
    name: "Manali",
    country: "Himachal Pradesh, India",
    region: "domestic",
    tagline: "Snow, rivers and endless mountain adventure.",
    image: "/uploads/2026/04/manali.jpg",
    bestTime: "May to June & Oct-Nov",
    duration: "4 Nights / 5 Days",
    price: "From ₹14,500 per person",
    summary:
      "Manali is where roaring rivers meet snow-capped peaks. From Solang Valley adventures to Atal Tunnel and Old Manali cafés, it's a complete mountain holiday.",
    highlights: [
      "Solang Valley adventure sports",
      "Rohtang / Atal Tunnel",
      "Hadimba Temple",
      "Old Manali cafés",
      "Beas River riverside",
    ],
    gallery: [
      "/manali/1.jpg",
      "/manali/2.jpg",
      "/manali/3.jpg",
      "/manali/4.jpg",
      "/manali/5.jpg",
      "/manali/6.jpg",
      "/manali/7.jpg",
      "/manali/8.jpg",
      "/manali/9.jpg",
      "/manali/10.jpg",
      "/manali/11.jpg",
      "/manali/12.jpg",
    ],
  },
  {
    slug: "goa",
    name: "Goa",
    country: "Goa, India",
    region: "domestic",
    tagline: "Sun, sand, parties and Portuguese heritage.",
    image: "/uploads/2026/04/goa.jpg",
    bestTime: "November to February",
    duration: "3 Nights / 4 Days",
    price: "From ₹10,500 per person",
    summary:
      "Goa is India's beach capital — golden shores, lively shacks, water sports and a laid-back Portuguese soul. Equally great for groups, families and couples.",
    highlights: [
      "North & South Goa beaches",
      "Water sports at Baga & Calangute",
      "Old Goa churches",
      "Cruise on the Mandovi river",
      "Anjuna flea market",
    ],
    gallery: [
      "/goa/1.jpg",
      "/goa/2.jpg",
      "/goa/3.jpg",
      "/goa/4.jpg",
      "/goa/5.jpg",
      "/goa/6.jpg",
      "/goa/7.jpg",
      "/goa/8.jpg",
      "/goa/9.jpg",
      "/goa/10.jpg",
      "/goa/11.jpg",
      "/goa/12.jpg",
      "/goa/13.jpg",
      "/goa/14.jpg",
      "/goa/15.jpg",
      "/goa/16.jpg",
    ],
  },
  {
    slug: "kashmir",
    name: "Kashmir",
    country: "Jammu & Kashmir, India",
    region: "domestic",
    tagline: "Paradise on Earth — lakes, meadows and mountains.",
    image: "/uploads/2026/04/kashmir.jpg",
    bestTime: "March to October",
    duration: "5 Nights / 6 Days",
    price: "From ₹18,000 per person",
    summary:
      "Kashmir's Dal Lake, Mughal gardens and Gulmarg meadows are the stuff of dreams. Houseboats, gondola rides and snow make it unforgettable in every season.",
    highlights: [
      "Dal Lake houseboat stay",
      "Gulmarg Gondola",
      "Pahalgam & Betaab Valley",
      "Mughal gardens of Srinagar",
      "Sonamarg day trip",
    ],
    gallery: [
      "/kashmir/1.jpg",
      "/kashmir/2.jpg",
      "/kashmir/3.jpg",
      "/kashmir/4.jpg",
      "/kashmir/5.jpg",
      "/kashmir/6.jpg",
      "/kashmir/7.jpg",
      "/kashmir/8.jpg",
      "/kashmir/9.jpg",
      "/kashmir/10.jpg",
      "/kashmir/11.jpg",
      "/kashmir/12.jpg",
      "/kashmir/13.jpg",
      "/kashmir/14.jpg",
      "/kashmir/15.jpg",
      "/kashmir/16.jpg",
      "/kashmir/17.jpg",
      "/kashmir/18.jpg",
      "/kashmir/19.jpg",
      "/kashmir/20.jpg",
      "/kashmir/21.jpg",
      "/kashmir/22.jpg",
      "/kashmir/23.jpg",
      "/kashmir/24.jpg",
      "/kashmir/25.jpg",
      "/kashmir/26.jpg",
      "/kashmir/27.jpg",
      "/kashmir/28.jpg",
    ],
  },
  {
    slug: "rajasthan",
    name: "Rajasthan",
    country: "Rajasthan, India",
    region: "domestic",
    tagline: "Forts, palaces and the colours of royal India.",
    image: "/uploads/2026/04/rajasthan.jpg",
    bestTime: "October to March",
    duration: "6 Nights / 7 Days",
    price: "From ₹22,000 per person",
    summary:
      "Rajasthan is a land of maharajas — amber forts, desert dunes, lake palaces and vibrant bazaars across Jaipur, Udaipur, Jodhpur and Jaisalmer.",
    highlights: [
      "Jaipur City Palace & Amber Fort",
      "Udaipur Lake Pichola",
      "Jaisalmer desert camp",
      "Jodhpur Mehrangarh Fort",
      "Pushkar fair (seasonal)",
    ],
    gallery: [
      "/uploads/2026/04/rajasthan.jpg",
      "/uploads/2026/04/rajasthan.jpg",
      "/uploads/2026/04/goa.jpg",
    ],
  },
  {
    slug: "kerala",
    name: "Kerala",
    country: "Kerala, India",
    region: "domestic",
    tagline: "Backwaters, tea hills and Ayurveda.",
    image: "/uploads/2026/04/kerala.jpg",
    bestTime: "September to March",
    duration: "4 Nights / 5 Days",
    price: "From ₹16,000 per person",
    summary:
      "God's Own Country charms with houseboats on the backwaters, misty Munnar tea plantations and the cultural rhythms of Kochi and Alleppey.",
    highlights: [
      "Alleppey houseboat cruise",
      "Munnar tea plantations",
      "Kochi fort & Chinese nets",
      "Thekkady wildlife",
      "Ayurvedic wellness",
    ],
    gallery: [
      "/uploads/2026/04/kerala.jpg",
      "/uploads/2026/04/kerala.jpg",
      "/uploads/2026/04/goa.jpg",
    ],
    subDestinations: [
      {
        slug: "alleppey",
        name: "Alleppey",
        tagline: "Venice of the East — backwaters, houseboats and serene lagoons.",
        image: "https://images.unsplash.com/photo-1593693397690-36240ae49ffb?w=800&q=80",
        highlights: [
          "Overnight houseboat cruise on the backwaters",
          "Alleppey beach and lighthouse",
          "Vembanad Lake bird watching",
          "Traditional Kerala houseboat cuisine",
          "Kuttanad rice bowl region",
        ],
        gallery: [
          "https://images.unsplash.com/photo-1593693397690-36240ae49ffb?w=800&q=80",
        ],
      },
      {
        slug: "kochi",
        name: "Kochi",
        tagline: "Queen of the Arabian Sea — colonial forts, Chinese nets and spice markets.",
        image: "https://images.unsplash.com/photo-1590073242678-70ee3fc28f8e?w=800&q=80",
        highlights: [
          "Fort Kochi and Chinese fishing nets",
          "Mattancherry Palace & Jewish Synagogue",
          "Marine Drive walkway",
          "Kerala Kathakali performance",
          "Spice market and local cuisine",
        ],
        gallery: [
          "https://images.unsplash.com/photo-1590073242678-70ee3fc28f8e?w=800&q=80",
        ],
      },
      {
        slug: "kovalam",
        name: "Kovalam",
        tagline: "Golden beaches, lighthouse views and Ayurvedic wellness.",
        image: "https://images.unsplash.com/photo-1591025207163-942350e47db2?w=800&q=80",
        highlights: [
          "Lighthouse Beach & Vizhinjam Beach",
          "Kovalam Ayurvedic spa treatments",
          "Sunset at the lighthouse",
          "Water sports and surfing",
          "Fresh seafood shacks",
        ],
        gallery: [
          "https://images.unsplash.com/photo-1591025207163-942350e47db2?w=800&q=80",
        ],
      },
      {
        slug: "kozhikode",
        name: "Kozhikode",
        tagline: "City of spices — historic trading port and culinary capital.",
        image: "https://images.unsplash.com/photo-1586351011005-19c4f9f7618f?w=800&q=80",
        highlights: [
          "Kozhikode Beach & pier",
          "Beypore ancient shipbuilding yard",
          "Kappad Beach — Vasco da Gama landing",
          "Thusharagiri Waterfalls",
          "Kozhikode biryani & halwa",
        ],
        gallery: [
          "https://images.unsplash.com/photo-1586351011005-19c4f9f7618f?w=800&q=80",
        ],
      },
      {
        slug: "munnar",
        name: "Munnar",
        tagline: "Tea gardens, misty hills and breathtaking valleys.",
        image: "https://images.unsplash.com/photo-1564005871064-57f01e0432b2?w=800&q=80",
        highlights: [
          "Rolling tea plantation walks",
          "Eravikulam National Park & Nilgiri Tahr",
          "Mattupetty Dam & boating",
          "Kundala Lake and Echo Point",
          "Tea museum and tasting",
        ],
        gallery: [
          "https://images.unsplash.com/photo-1564005871064-57f01e0432b2?w=800&q=80",
        ],
      },
      {
        slug: "thekkady",
        name: "Thekkady",
        tagline: "Wildlife, spice plantations and Periyar Lake.",
        image: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80",
        highlights: [
          "Periyar Wildlife Sanctuary boat safari",
          "Spice plantation tour",
          "Bamboo rafting in Periyar Lake",
          "Elephant ride and nature walk",
          "Ayurvedic massage experiences",
        ],
        gallery: [
          "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800&q=80",
        ],
      },
      {
        slug: "thrissur",
        name: "Thrissur",
        tagline: "Cultural capital — temples, festivals and Kerala's vibrant heart.",
        image: "https://images.unsplash.com/photo-1601877643985-6b09c32c470f?w=800&q=80",
        highlights: [
          "Vadakkunnathan Temple",
          "Thrissur Pooram festival",
          "Athirappilly Waterfalls",
          "Kerala Kalamandalam",
          "Guruvayur Temple visit",
        ],
        gallery: [
          "https://images.unsplash.com/photo-1601877643985-6b09c32c470f?w=800&q=80",
        ],
      },
      {
        slug: "vagamon",
        name: "Vagamon",
        tagline: "Offbeat hill station — pine forests, meadows and tranquillity.",
        image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
        highlights: [
          "Vagamon meadows and pine forest",
          "Paragliding and trekking",
          "Murugan Mala and Kurisumala",
          "Tea garden walks",
          "Camping under the stars",
        ],
        gallery: [
          "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
        ],
      },
      {
        slug: "wayanad",
        name: "Wayanad",
        tagline: "Lush jungles, ancient caves and spice-laden hills.",
        image: "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&q=80",
        highlights: [
          "Edakkal Caves ancient petroglyphs",
          "Chembra Peak heart-shaped lake",
          "Wayanad Wildlife Sanctuary",
          "Soochipara and Meenmutty Falls",
          "Banasura Sagar Dam boating",
        ],
        gallery: [
          "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?w=800&q=80",
        ],
      },
    ],
  },
  {
    slug: "rishikesh",
    name: "Rishikesh",
    country: "Uttarakhand, India",
    region: "domestic",
    tagline: "Yoga, Ganga and adventure by the river.",
    image: "/rishikesh/1.jpg",
    bestTime: "September to April",
    duration: "2 Nights / 3 Days",
    price: "From ₹8,000 per person",
    summary:
      "Rishikesh is the yoga capital and India's adventure hub — river rafting, cliff jumps, Ganga aarti and peaceful ashrams along the Himalayan foothills.",
    highlights: [
      "Ganga Aarti at Triveni Ghat",
      "White-water rafting",
      "Laxman Jhula & Ram Jhula",
      "Yoga & meditation retreats",
      "Beatles Ashram",
    ],
    gallery: [
      "/rishikesh/1.jpg",
      "/rishikesh/2.jpg",
      "/rishikesh/3.jpg",
      "/rishikesh/4.jpg",
      "/rishikesh/5.jpg",
      "/rishikesh/6.jpg",
      "/rishikesh/7.jpg",
      "/rishikesh/8.jpg",
      "/rishikesh/9.jpg",
      "/rishikesh/10.jpg",
      "/rishikesh/11.jpg",
      "/rishikesh/12.jpg",
    ],
  },
  {
    slug: "nainital",
    name: "Nainital",
    country: "Uttarakhand, India",
    region: "domestic",
    tagline: "The Lake District of India — shimmering lakes and Himalayan panoramas.",
    image: "/nainital/1.jpg",
    bestTime: "March to June & September to November",
    duration: "3 Nights / 4 Days",
    price: "From ₹10,000 per person",
    summary:
      "Nainital, the charming Lake District of India, is a picturesque hill station nestled around the emerald Naini Lake in the Kumaon Himalayas. Surrounded by lush forests and snow-capped peaks, it offers serene boat rides, scenic viewpoints like Snow View and Tiffin Top, colonial-era architecture, and tranquil temple visits. A perfect escape for families, couples and nature lovers seeking peace and beauty in the hills.",
    highlights: [
      "Boating on the pristine Naini Lake",
      "Sunrise at Snow View Point",
      "Tiffin Top (Dorothy's Seat) trek",
      "Naina Devi Temple and Cave Garden",
      "Mall Road shopping and cafés",
      "Eco Cave Gardens and zoo",
    ],
    gallery: [
      "/nainital/1.jpg",
      "/nainital/2.jpg",
      "/nainital/3.jpg",
      "/nainital/4.jpg",
      "/nainital/5.jpg",
      "/nainital/6.jpg",
      "/nainital/7.jpg",
      "/nainital/8.jpg",
      "/nainital/9.jpg",
      "/nainital/10.jpg",
      "/nainital/11.jpg",
      "/nainital/12.jpg",
      "/nainital/13.jpg",
      "/nainital/14.jpg",
    ],
  },
  {
    slug: "haridwar",
    name: "Haridwar",
    country: "Uttarakhand, India",
    region: "domestic",
    tagline: "The Gateway to God — sacred Ganga, ancient temples and spiritual vibes.",
    image: "/haridwar/1.jpg",
    bestTime: "October to March",
    duration: "2 Nights / 3 Days",
    price: "From ₹6,500 per person",
    summary:
      "Haridwar, the Gateway to the Gods, is one of the holiest cities in India. Situated on the banks of the Ganga, it is famous for the mesmerising Ganga Aarti at Har Ki Pauri, ancient temples like Mansa Devi and Chandi Devi, and the sacred ghats where pilgrims gather for centuries-old rituals. A perfect spiritual getaway blended with rich culture and serene river views.",
    highlights: [
      "Ganga Aarti at Har Ki Pauri",
      "Mansa Devi Temple ropeway ride",
      "Chandi Devi Temple trek",
      "Evening boat ride on the Ganga",
      "Explore the bustling local markets",
      "Visit Bharat Mata Mandir",
    ],
    gallery: [
      "/haridwar/1.jpg",
      "/haridwar/2.jpg",
      "/haridwar/3.jpg",
      "/haridwar/4.jpg",
      "/haridwar/5.jpg",
      "/haridwar/6.jpg",
      "/haridwar/7.jpg",
      "/haridwar/8.jpg",
      "/haridwar/9.jpg",
      "/haridwar/10.jpg",
    ],
  },
  {
    slug: "dehradun",
    name: "Dehradun",
    country: "Uttarakhand, India",
    region: "domestic",
    tagline: "The Doon Valley — lush valleys, colonial charm and Himalayan views.",
    image: "/dehradun/1.jpg",
    bestTime: "March to June & September to November",
    duration: "3 Nights / 4 Days",
    price: "From ₹9,000 per person",
    summary:
      "Dehradun, the capital of Uttarakhand, is a picturesque city nestled in the Doon Valley between the Shivaliks and the Himalayas. Known for its colonial-era architecture, prestigious boarding schools, lush botanical gardens and as the gateway to Mussoorie, it offers a perfect blend of urban comfort and natural beauty. Explore Robber's Cave, Sahastradhara, and enjoy stunning Himalayan panoramas.",
    highlights: [
      "Visit Robber's Cave (Guchhupani)",
      "Sahastradhara sulphur springs",
      "Forest Research Institute walk",
      "Mindrolling Monastery & Buddha Temple",
      "Tapkeshwar Temple",
      "Day trip to Mussoorie & Kempty Falls",
    ],
    gallery: [
      "/dehradun/1.jpg",
      "/dehradun/2.jpg",
      "/dehradun/3.jpg",
      "/dehradun/4.jpg",
      "/dehradun/5.jpg",
      "/dehradun/6.jpg",
      "/dehradun/7.jpg",
      "/dehradun/8.jpg",
      "/dehradun/9.jpg",
      "/dehradun/10.jpg",
    ],
  },
  {
    slug: "sikkim",
    name: "Sikkim",
    country: "Sikkim, India",
    region: "domestic",
    tagline: "Monasteries, rhododendrons and Kanchenjunga views.",
    image: "/uploads/2026/04/shimla.jpg",
    bestTime: "March to June & October to December",
    duration: "5 Nights / 6 Days",
    price: "From ₹16,000 per person",
    summary:
      "Sikkim is a serene Himalayan gem — Buddhist monasteries, the high-altitude Gurudongmar Lake, colourful Gangtok markets and breathtaking views of the Kanchenjunga range.",
    highlights: [
      "Gangtok & MG Marg",
      "Tsomgo (Changu) Lake",
      "Gurudongmar Lake",
      "Rumtek Monastery",
      "Kanchenjunga views",
    ],
    gallery: [
      "/sikkim/1.jpg",
      "/sikkim/2.jpg",
      "/sikkim/3.jpg",
      "/sikkim/4.jpg",
      "/sikkim/5.jpg",
      "/sikkim/6.jpg",
      "/sikkim/7.jpg",
      "/sikkim/8.jpg",
      "/sikkim/9.jpg",
      "/sikkim/10.jpg",
      "/sikkim/11.jpg",
      "/sikkim/12.jpg",
      "/sikkim/13.jpg",
    ],
  },
  {
    slug: "darjeeling",
    name: "Darjeeling",
    country: "West Bengal, India",
    region: "domestic",
    tagline: "The Queen of Hills — tea gardens, toy trains and Himalayan panoramas.",
    image: "/darjeeling/1.jpg",
    bestTime: "March to June & September to November",
    duration: "4 Nights / 5 Days",
    price: "From ₹14,000 per person",
    summary:
      "Darjeeling, the Queen of the Hills, is a breathtaking hill station in West Bengal's Himalayan foothills. Famous for its lush tea gardens, the UNESCO-listed Darjeeling Himalayan Railway (Toy Train), and spectacular views of the Kanchenjunga range, it offers a perfect blend of natural beauty, colonial charm and rich culture. Explore Tiger Hill at sunrise, visit serene monasteries, and sip the world-famous Darjeeling tea amidst misty mountains.",
    highlights: [
      "Tiger Hill sunrise over Kanchenjunga",
      "Darjeeling Himalayan Railway (Toy Train) ride",
      "Visit lush tea gardens with tasting sessions",
      "Peaceful Buddhist monasteries — Ghoom & Dali",
      "Batasia Loop & War Memorial",
      "Rock Garden & Gangamaya Park",
    ],
    gallery: [
      "/darjeeling/1.jpg",
      "/darjeeling/2.jpg",
      "/darjeeling/3.jpg",
      "/darjeeling/4.jpg",
      "/darjeeling/5.jpg",
      "/darjeeling/6.jpg",
      "/darjeeling/7.jpg",
      "/darjeeling/8.jpg",
      "/darjeeling/9.jpg",
      "/darjeeling/10.jpg",
      "/darjeeling/11.jpg",
      "/darjeeling/12.jpg",
      "/darjeeling/13.jpg",
    ],
  },
  {
    slug: "varanasi",
    name: "Varanasi",
    country: "Uttar Pradesh, India",
    region: "domestic",
    tagline: "The spiritual heart of India on the banks of the sacred Ganga.",
    image: "/varanasi/1.jpg",
    bestTime: "October to March",
    duration: "3 Nights / 4 Days",
    price: "From ₹10,999 per person",
    summary:
      "Varanasi, also known as Kashi, is one of the oldest living cities in the world and the spiritual heart of India. Witness the mesmerising Ganga Aarti at Dashashwamedh Ghat, take an early morning boat ride on the sacred River Ganga, and explore ancient temples like Kashi Vishwanath. A short trip to Sarnath reveals the peaceful Buddhist heritage where Lord Buddha gave his first sermon.",
    highlights: [
      "Ganga Aarti at Dashashwamedh Ghat",
      "Early morning boat ride on the River Ganga",
      "Kashi Vishwanath Temple",
      "Sarnath — the Buddhist heritage site",
      "One of the oldest living cities with deep spiritual vibes",
    ],
    gallery: [
      "/varanasi/1.jpg",
      "/varanasi/2.jpg",
      "/varanasi/3.jpg",
      "/varanasi/4.jpg",
      "/varanasi/5.jpg",
      "/varanasi/6.jpg",
      "/varanasi/7.jpg",
      "/varanasi/8.jpg",
      "/varanasi/9.jpg",
      "/varanasi/10.jpg",
      "/varanasi/11.jpg",
      "/varanasi/12.jpg",
      "/varanasi/13.jpg",
    ],
  },
];

export const testimonials = [
  {
    name: "Priya Sharma",
    location: "Delhi",
    quote:
      "Our Bali trip was flawlessly planned. Hotels, transfers and tours were all on time. Truly hassle-free holidays!",
    rating: 5,
  },
  {
    name: "Rahul Verma",
    location: "Noida",
    quote:
      "Booked a Rajasthan family tour. Great pricing and the team stayed in touch throughout the trip. Highly recommended.",
    rating: 5,
  },
  {
    name: "Anita & Mohit",
    location: "Gurgaon",
    quote:
      "Our Maldives honeymoon was straight out of a dream. Thank you Get Set Go Holidays for the perfect arrangements.",
    rating: 5,
  },
  {
    name: "Sandeep Rao",
    location: "Pune",
    quote:
      "Visa and flight booking handled end-to-end. Smooth, transparent and reliable service every step of the way.",
    rating: 4,
  },
  {
    name: "Meera Nair",
    location: "Bengaluru",
    quote:
      "Kerala backwaters houseboat was the highlight. The itinerary was well paced and the driver was excellent.",
    rating: 5,
  },
  {
    name: "Karan Singh",
    location: "Lucknow",
    quote:
      "Group trip to Thailand was so well organised. Great value and zero stress. We'll travel with them again.",
    rating: 5,
  },
];

export function getDestination(slug) {
  return destinations.find((d) => d.slug === slug);
}

export const blog = [
  {
    slug: "best-time-to-visit-kashmir",
    title: "Best Time to Visit Kashmir — A Seasonal Travel Guide",
    excerpt:
      "From tulip gardens in spring to snowy Gulmarg in winter, here's when to plan your perfect Kashmir escape.",
    image: "/uploads/2026/04/kashmir.jpg",
    date: "2026-04-12",
    category: "Domestic",
    author: "Get Set Go Holidays",
    readTime: "5 min read",
    content: [
      "Kashmir is often called Paradise on Earth, and for good reason. Every season paints the valley in a different mood — making it one of the most versatile destinations in India.",
      "Spring (March to May) brings the famous tulip festival in Srinagar, with Indira Gandhi Memorial Tulip Garden bursting into colour. The weather is pleasant, perfect for shikara rides on Dal Lake.",
      "Summer (June to August) is ideal for family trips and sightseeing in Pahalgam, Sonamarg and Gulmarg. The meadows are lush and the skies are clear.",
      "Autumn (September to November) covers the Chinars in gold and crimson — a photographer's dream and the best time for peaceful getaways.",
      "Winter (December to February) turns Gulmarg into a snow paradise. If you love skiing or the Gondola, this is your season.",
      "Whenever you choose to go, our team handles stays, transfers and sightseeing so you can simply soak in the beauty.",
    ],
  },
  {
    slug: "bali-travel-tips-for-first-timers",
    title: "Bali Travel Tips for First-Timers",
    excerpt:
      "Everything you need to know before your first trip to the Island of the Gods — from visa to local etiquette.",
    image: "/uploads/2026/04/bali.jpg",
    date: "2026-03-28",
    category: "International",
    author: "Get Set Go Holidays",
    readTime: "6 min read",
    content: [
      "Bali blends golden beaches, spiritual temples and vibrant culture. If it's your first visit, a little planning goes a long way.",
      "Most Indian travellers can get a visa on arrival or an e-VOA. Keep your passport valid for at least six months and carry a return ticket.",
      "Stay zones matter: Seminyak and Canggu are great for beaches and nightlife, while Ubud is the hub for culture, rice terraces and yoga.",
      "Respect temple customs — carry a sarong, dress modestly and avoid pointing feet at shrines.",
      "Local transport is easiest with a private cab. We arrange sanitized vehicles with experienced drivers for stress-free exploration.",
      "With the right plan, Bali is safe, welcoming and unforgettable. Talk to us for a customised itinerary.",
    ],
  },
  {
    slug: "how-to-plan-a-budget-honeymoon",
    title: "How to Plan a Budget-Friendly Honeymoon",
    excerpt:
      "A dream honeymoon doesn't have to break the bank. Smart tips to plan a romantic trip on a budget.",
    image: "/uploads/2026/04/maldives.jpg",
    date: "2026-03-15",
    category: "Honeymoon",
    author: "Get Set Go Holidays",
    readTime: "4 min read",
    content: [
      "Your honeymoon should feel magical, not stressful. With smart choices you can enjoy luxury experiences without overspending.",
      "Travel in the shoulder season. Prices for hotels and flights drop just before and after peak months, with fewer crowds.",
      "Pick one or two experiences to splurge on — like a candle-light dinner or an overwater villa night — and keep the rest simple.",
      "Book packages instead of separate components. Bundled stays, transfers and sightseeing almost always cost less.",
      "Use a trusted planner. We negotiate the best rates and handle everything, so you only focus on each other.",
    ],
  },
  {
    slug: "top-5-family-destinations-in-india",
    title: "Top 5 Family Destinations in India",
    excerpt:
      "Planning a trip with kids and grandparents? These Indian destinations offer fun for every age group.",
    image: "/uploads/2026/04/goa.jpg",
    date: "2026-02-20",
    category: "Family",
    author: "Get Set Go Holidays",
    readTime: "5 min read",
    content: [
      "India is incredibly family-friendly once you pick the right place. Here are five favourites our travellers love.",
      "Goa — beaches, water sports and easy relaxed days that work for all ages.",
      "Rajasthan — forts, palaces and colourful culture that fascinate kids and adults alike.",
      "Kerala — backwater cruises and gentle hill stations perfect for multi-generational trips.",
      "Shimla & Manali — snow play for children and scenic calm for grandparents.",
      "Kashmir — houseboats and gardens that create memories for the whole family.",
      "We design balanced itineraries with rest days, kid-friendly meals and comfortable pacing.",
    ],
  },
  {
    slug: "bali-island-of-gods-tropical-escape",
    title: "Bali – The Island of Gods: Your Dream Tropical Escape",
    excerpt:
      "From ancient temples and emerald rice terraces to golden beaches and vibrant nightlife — discover why Bali is every traveller's dream destination.",
    image: "/uploads/2026/04/bali.jpg",
    date: "2026-07-15",
    category: "International",
    author: "Get Set Go Holidays",
    readTime: "7 min read",
    content: [
      "## Bali – The Island of Gods: Your Dream Tropical Escape",
      "Bali is one of the world's most loved travel destinations, offering a perfect blend of breathtaking beaches, lush green landscapes, ancient temples, vibrant culture, thrilling adventures, and luxurious resorts. Known as the \"Island of Gods,\" Bali is more than just an island — it's an experience that leaves every traveller with unforgettable memories.",
      "Located in Indonesia, Bali attracts millions of visitors every year, including a large number of Indian travellers seeking a relaxing holiday, honeymoon, family vacation or adventure-filled getaway. From sunrise over volcanic mountains to spectacular sunsets by the Indian Ocean, every corner of Bali offers something unique.",
      "## Why Visit Bali?",
      "Bali is a destination where nature, spirituality, and modern luxury coexist beautifully. The island is famous for its warm hospitality, affordable luxury, delicious cuisine, wellness retreats, and vibrant nightlife, making it an ideal destination for couples, families, solo travellers, and groups alike.",
      "## Best Time to Visit Bali",
      "The ideal time to visit Bali is between April and October, when the weather is dry, sunny, and perfect for sightseeing, island tours, beach activities, and outdoor adventures. The November to March season experiences occasional rainfall but also offers lush green landscapes, fewer crowds, and attractive hotel deals, making it suitable for budget-conscious travellers.",
      "## Top Places to Explore in Bali",
      "### Ubud – The Cultural Heart of Bali",
      "Surrounded by lush rice terraces and tropical forests, Ubud is known for its traditional art, yoga retreats, Balinese culture and peaceful atmosphere. Visit the famous Tegalalang Rice Terraces, Sacred Monkey Forest, Bali Swing, and explore local art markets for an authentic Balinese experience.",
      "### Kuta – Beaches & Nightlife",
      "Kuta is one of Bali's most popular tourist areas, offering golden beaches, surfing spots, shopping streets, lively cafes and exciting nightlife. It's the perfect place to relax by the beach during the day and enjoy entertainment after sunset.",
      "### Seminyak – Luxury and Lifestyle",
      "Seminyak is known for its luxury resorts, stylish beach clubs, fine dining restaurants, boutique shopping and spectacular sunset views. It's an excellent destination for travellers looking for comfort and sophistication.",
      "### Nusa Penida – Nature's Masterpiece",
      "Just a short boat ride from Sanur Port, Nusa Penida is famous for dramatic cliffs, crystal-clear waters, hidden beaches, and iconic viewpoints like Kelingking Beach, Diamond Beach, and Angel's Billabong. It's a paradise for photographers and adventure lovers.",
      "### Uluwatu – Clifftop Beauty",
      "Home to the magnificent Uluwatu Temple, this region offers breathtaking ocean views, world-famous surfing beaches and the mesmerising Kecak Fire Dance performed during sunset.",
      "### Gili Islands – Tropical Escape",
      "Although located near Lombok, the Gili Islands are often included in Bali itineraries. With white sandy beaches, turquoise waters, snorkelling, scuba diving, and a peaceful atmosphere, they provide the perfect island escape.",
      "## Best Things to Do in Bali",
      "Witness the magical sunset at Uluwatu Temple with the traditional Kecak Dance, experience the famous Bali Swing overlooking lush rice terraces, enjoy thrilling ATV rides through forests and villages, relax with a traditional Balinese spa treatment, explore waterfalls like Tegenungan and Kanto Lampo, visit Pura Tirta Empul Temple and Tirta Gangga Water Palace, go snorkelling or scuba diving around Nusa Penida and the Gili Islands, enjoy water sports at Nusa Dua, watch the sunrise trek at Kintamani Mount Batur, and spend an evening at Bali's famous beach clubs.",
      "## Balinese Culture",
      "Bali is deeply rooted in Hindu traditions, making it unique within Indonesia. Beautiful temples, colourful ceremonies, daily offerings known as Canang Sari, and traditional dance performances showcase the island's rich cultural heritage. Visitors are welcomed with warmth and genuine hospitality, making every experience feel special.",
      "## Why Bali is the Perfect Destination for Every Traveler",
      "Bali has become one of the most preferred international destinations for Indian tourists because it offers visa-friendly travel, excellent connectivity, affordable luxury, delicious vegetarian food options, exciting adventure activities, and beautiful resorts suitable for every budget. Whether it's a honeymoon, family holiday, friends' trip, or corporate getaway, Bali provides unforgettable experiences without requiring an extravagant budget.",
      "## A Journey to Remember",
      "Bali is a destination where every sunrise promises adventure and every sunset brings peace. From serene temples and emerald rice terraces to vibrant beaches and luxurious resorts, the island offers a perfect balance of relaxation, culture, and excitement. If you're planning your next international vacation, Bali deserves a place at the top of your travel bucket list.",
    ],
  },
  {
    slug: "dubai-where-every-day-feels-like-a-new-adventure",
    title: "Dubai: Where Every Day Feels Like a New Adventure",
    excerpt:
      "From the world's tallest building to golden desert dunes — discover why Dubai is a destination where innovation meets tradition.",
    image: "/uploads/2026/04/dubai.jpg",
    date: "2026-07-15",
    category: "International",
    author: "Get Set Go Holidays",
    readTime: "6 min read",
    content: [
      "## Dubai: Where Every Day Feels Like a New Adventure",
      "Dubai is a city that constantly surprises you. One moment you're standing at the top of the world's tallest building, and the next you're watching the sun set over golden sand dunes. It is a destination where innovation meets tradition, offering unforgettable experiences for every kind of traveller. Whether you're a family, a couple, a solo explorer, or an adventure enthusiast, Dubai promises memories that last a lifetime.",
      "## A Skyline That Inspires",
      "Dubai's skyline is one of the most iconic in the world. Marvel at the magnificent Burj Khalifa, admire the futuristic Museum of the Future, stroll around the luxurious Palm Jumeirah, and enjoy spectacular views from Dubai Marina. Every landmark reflects the city's ambition and architectural brilliance.",
      "## A Blend of Tradition and Modernity",
      "Beyond its glamorous lifestyle, Dubai proudly preserves its rich heritage. Explore the charming Al Fahidi Historical District, shop for gold and spices in the traditional souks, and enjoy a peaceful abra ride across Dubai Creek. These authentic experiences offer a glimpse into the city's fascinating past.",
      "## Exciting Things to Do in Dubai",
      "Dubai offers endless activities for travellers of all ages. Visit the Burj Khalifa and enjoy panoramic city views, experience an unforgettable Desert Safari with dune bashing, camel rides, and a traditional BBQ dinner, relax at Jumeirah Beach or explore the vibrant Dubai Marina, shop at the world-famous Dubai Mall and watch the spectacular Dubai Fountain Show, visit Palm Jumeirah and the incredible Atlantis Aquaventure Waterpark, explore the Museum of the Future, enjoy thrilling adventures like Skydiving, Jet Skiing, Ziplining, or a Luxury Yacht Cruise, and spend a fun-filled day at IMG Worlds of Adventure, Motiongate Dubai, or Global Village.",
      "## A Paradise for Food Lovers",
      "Dubai is home to one of the world's most diverse food scenes. From authentic Emirati cuisine and Middle Eastern specialties to Indian, Asian, and international fine dining, every meal is a delightful culinary experience.",
      "## Shopping Beyond Expectations",
      "Shopping in Dubai is more than just retail therapy. Browse luxury brands at Dubai Mall, enjoy indoor skiing at Mall of the Emirates, or discover handcrafted souvenirs, perfumes, spices, and gold jewellery in the traditional souks.",
      "## Best Time to Visit Dubai",
      "The ideal time to visit Dubai is November to March, when the weather is cool and pleasant, making it perfect for sightseeing, desert safaris, beach outings, yacht cruises, and outdoor festivals.",
      "### November – March",
      "Best season for sightseeing, beaches, shopping festivals, and outdoor activities.",
      "### April – May",
      "Warm weather with fewer crowds and attractive hotel offers.",
      "### June – September",
      "Hot summer season, ideal for enjoying indoor attractions, shopping malls, aquariums, and water parks at discounted prices.",
      "### October",
      "Pleasant weather returns, making it a great time to start exploring outdoor attractions again.",
      "## Why Everyone Should Visit Dubai",
      "Dubai is a destination where luxury, adventure, culture, entertainment, and world-class hospitality come together. Whether you're looking for a romantic honeymoon, a family vacation, an adventure-filled escape, or a luxurious holiday, Dubai offers experiences that suit every traveller and every budget. From breathtaking skyscrapers to peaceful deserts, vibrant nightlife to cultural treasures, every moment in Dubai is truly extraordinary.",
    ],
  },
  {
    slug: "thailand-the-land-of-smiles",
    title: "Thailand: The Land of Smiles",
    excerpt:
      "From Bangkok's vibrant streets to Phuket's turquoise waters — discover why Thailand is the ultimate tropical paradise for every traveller.",
    image: "/uploads/2026/04/thailand.jpg",
    date: "2026-07-15",
    category: "International",
    author: "Get Set Go Holidays",
    readTime: "7 min read",
    content: [
      "## Thailand: The Land of Smiles",
      "Thailand is one of the world's most popular travel destinations, known for its beautiful beaches, tropical islands, ancient temples, vibrant cities, delicious cuisine, and warm hospitality. From the bustling streets of Bangkok to the crystal-clear waters of Phuket and Krabi, Thailand offers the perfect blend of culture, adventure, relaxation, and luxury, making it an ideal destination for every type of traveller.",
      "## Why Do People Visit Thailand?",
      "People visit Thailand for its breathtaking beaches, island-hopping experiences, rich cultural heritage, world-famous Thai food, exciting nightlife and affordable luxury. Whether it's a honeymoon, family vacation, adventure trip, or a relaxing getaway, Thailand offers unforgettable experiences with something for everyone.",
      "## Best Time to Visit Thailand",
      "Thailand welcomes travellers throughout the year, but the ideal time depends on the kind of holiday you're planning.",
      "### November to February",
      "Best season offering pleasant weather perfect for sightseeing, island tours, and outdoor adventures.",
      "### March to May",
      "Ideal for travellers who love beaches, water activities, and sunny days.",
      "### June to October",
      "Thailand transforms into a lush green paradise. Occasional rain showers occur, landscapes become even more beautiful, crowds are smaller, and hotels often offer attractive deals.",
      "## Discover Thailand's Most Beautiful Destinations",
      "### Bangkok – The City That Never Stops Exploring",
      "Thailand's capital is energetic, colourful and endlessly fascinating. Wander through the magnificent Grand Palace, admire the beauty of Wat Arun as it reflects the evening sun, cruise along the Chao Phraya River, or spend hours exploring bustling markets and luxury malls. Bangkok delivers an unforgettable introduction to Thailand.",
      "### Phuket – A Tropical Paradise",
      "Thailand's largest island is famous for its luxurious resorts, lively beaches, exciting nightlife, and unforgettable island tours. From relaxing at Patong Beach to exploring the breathtaking Phi Phi Islands and visiting the iconic Big Buddha, Phuket offers the perfect balance of adventure and relaxation.",
      "### Krabi – Nature's Masterpiece",
      "Dramatic limestone cliffs, turquoise lagoons, hidden beaches and peaceful surroundings — Krabi will steal your heart. Railay Beach, accessible only by boat, is considered one of the most beautiful beaches in the world. The famous Four Islands Tour, kayaking through mangrove forests, snorkelling in crystal-clear waters and climbing towering cliffs make Krabi a paradise for adventure lovers.",
      "### Pattaya – Entertainment Meets Relaxation",
      "Just a short drive from Bangkok, Pattaya offers something for everyone. Families can explore tropical gardens and Coral Island, couples can enjoy romantic beach sunsets, while groups of friends can experience the city's vibrant nightlife. From thrilling water sports to cultural attractions like the Sanctuary of Truth, Pattaya perfectly combines excitement with relaxation.",
      "## Experiences That Make Thailand Unforgettable",
      "Wake up early to watch monks collect alms along peaceful streets. Sail through emerald waters on a traditional long-tail boat. Dive beneath the sea to discover colourful coral reefs. Wander through floating markets filled with local delicacies and handcrafted souvenirs. Treat yourself to an authentic Thai massage or enjoy fresh seafood while watching the sun disappear into the horizon. Every experience adds another unforgettable chapter to your Thailand story.",
      "## Explore the World of Thai Food",
      "Thai cuisine is celebrated across the world, and tasting it in its country of origin is an experience in itself. Every dish combines fresh herbs, aromatic spices, and bold flavours that create a perfect balance of sweet, sour, salty, and spicy. From the famous Pad Thai and Tom Yum Soup to Green Curry and the irresistible Mango Sticky Rice, every meal introduces you to another side of Thailand's rich culinary heritage.",
      "## Why Thailand is Perfect for Every Traveler",
      "Whether you're planning a honeymoon, a family vacation, an adventure with friends, or your very first international trip, Thailand has something special waiting for you. Couples can enjoy romantic island escapes and luxurious spa experiences. Families will love the exciting attractions and beautiful beaches. Adventure enthusiasts can explore coral reefs, trek through jungles, or zipline above lush forests. Thailand is one of those rare destinations where every traveller leaves with a different story — but the same desire to return.",
      "## Final Words",
      "Thailand isn't just a place you visit — it's a destination you feel. It's the warmth of its people, the beauty of its landscapes, the richness of its traditions, and the joy found in every little experience. From sunrise over ancient temples to sunset on tropical islands, every day in Thailand offers something extraordinary. Are you ready to explore the Land of Smiles?",
    ],
  },
  {
    slug: "vietnam-journey-through-nature-culture-and-unforgettable-experiences",
    title: "Vietnam: A Journey Through Nature, Culture, and Unforgettable Experiences",
    excerpt:
      "From Ha Long Bay's emerald waters to Hoi An's lantern-lit streets — discover why Vietnam is Southeast Asia's most captivating destination.",
    image: "/uploads/2026/04/thailand.jpg",
    date: "2026-07-15",
    category: "International",
    author: "Get Set Go Holidays",
    readTime: "7 min read",
    content: [
      "## Vietnam: A Journey Through Nature, Culture, and Unforgettable Experiences",
      "Vietnam is one of Southeast Asia's most captivating destinations, offering a perfect blend of breathtaking landscapes, rich history, vibrant cities and world-famous cuisine. From the limestone islands of Ha Long Bay to the lantern-lit streets of Hoi An and the bustling energy of Ho Chi Minh City, every corner of Vietnam tells a unique story.",
      "For travellers looking for an affordable international holiday, Vietnam offers incredible value with diverse experiences suitable for honeymooners, families, solo travellers and adventure enthusiasts alike.",
      "## Why Visit Vietnam?",
      "Vietnam is a destination where every traveller can find something to love. Whether you're cruising through the emerald waters of Ha Long Bay, trekking the rice terraces of Sapa, exploring the ancient charm of Hoi An Ancient Town, relaxing on the beaches of Da Nang and Phu Quoc, or experiencing the lively nightlife of Ho Chi Minh City, Vietnam offers unforgettable memories at every step.",
      "The country is also known for its warm hospitality, fascinating history, delicious street food, and affordable luxury, making it an excellent choice for international vacations.",
      "## Best Time to Visit Vietnam",
      "The ideal time to visit Vietnam is October to April, when the weather is generally pleasant across most regions. During these months, travellers can comfortably explore cities, beaches, mountains, and islands.",
      "### October – December",
      "Cool weather, perfect for sightseeing.",
      "### January – April",
      "Great for beaches, cruises, and outdoor activities.",
      "### May – September",
      "Green landscapes and fewer crowds, with occasional rainfall in some regions.",
      "## Top Places to Visit in Vietnam",
      "### Hanoi",
      "The capital of Vietnam is famous for its centuries-old architecture, bustling Old Quarter, Hoan Kiem Lake, Ngoc Son Temple, Train Street and rich cultural heritage. It is the perfect place to experience traditional Vietnamese life while enjoying modern cafés and local markets.",
      "### Ha Long Bay",
      "A UNESCO World Heritage Site renowned for its thousands of limestone islands rising from emerald waters. An overnight cruise, kayaking, and sunset views make it one of Vietnam's most iconic destinations.",
      "### Sapa",
      "Nestled in the northern mountains, Sapa is known for its stunning rice terraces, scenic trekking routes, ethnic villages and breathtaking mountain landscapes. It is a paradise for nature lovers.",
      "### Da Nang",
      "Da Nang combines beautiful beaches with modern attractions such as the Golden Bridge at Ba Na Hills, Marble Mountains and the Dragon Bridge. It is one of Vietnam's fastest-growing tourist destinations.",
      "### Hoi An Ancient Town",
      "This UNESCO-listed ancient town is famous for its colourful lanterns, riverside cafés, historic architecture, tailor shops and romantic evening atmosphere.",
      "### Ho Chi Minh City",
      "Previously known as Saigon, this energetic city offers historical landmarks, vibrant nightlife, shopping malls, famous rooftop cafés and museums that showcase Vietnam's fascinating past.",
      "### Phu Quoc Island",
      "Located in the Gulf of Thailand, Phu Quoc is Vietnam's tropical paradise. With crystal-clear beaches, luxury resorts, island tours, snorkelling, VinWonders and spectacular sunset views, it is perfect for families and honeymooners alike.",
      "## Vietnamese Culture and Food",
      "Vietnam's culture reflects centuries of tradition, family values and hospitality. Ancient temples, colourful festivals, traditional markets and local crafts provide visitors with an authentic cultural experience.",
      "Vietnam is equally famous for its cuisine. Signature dishes include Pho, Banh Mi, Fresh Spring Rolls, Bun Cha and delicious Vietnamese coffee. Whether dining at a street-side café or an elegant restaurant, every meal is a culinary adventure.",
      "## Why Vietnam is Perfect for Every Traveller",
      "Vietnam offers something for everyone. Couples can enjoy romantic cruises and peaceful beaches, families can explore theme parks and cultural attractions, adventure lovers can trek mountains and discover caves, while food enthusiasts can indulge in some of Asia's finest street food. Its combination of affordability, natural beauty, modern infrastructure, and rich heritage makes Vietnam one of the best international destinations for Indian travellers.",
    ],
  },
];

export function getPost(slug) {
  return blog.find((p) => p.slug === slug);
}
