export const packageDetails = [
  {
    slug: "customized-tour-packages",
    title: "Customized Tour Packages",
    subtitle: "Tailor-made holidays crafted around your dreams",
    hero: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1920&q=80",
    sections: [
      {
        heading: "Your Trip, Your Way",
        body: "We believe every traveler has different preferences, which is why we don't just sell fixed packages—we create 100% customized tour packages according to your needs, budget, and travel style.",
      },
      {
        heading: "Who We Cater To",
        body: "Whether you're planning a family vacation, a honeymoon trip, a solo adventure, a group tour with friends, a corporate trip, a religious tour, or a weekend getaway, our team will plan everything for you from start to finish. You just need to tell us where you want to go, your travel dates, how many people are travelling, your approximate budget, and any special preferences you have. Based on that, we'll prepare a personalized itinerary that suits you perfectly.",
      },
    ],
    inclusions: [
      "Domestic & international flight tickets",
      "Hotel bookings (budget, deluxe, premium, luxury)",
      "Airport & railway station transfers",
      "Private cabs for sightseeing",
      "Breakfast and meals (as per package)",
      "Cruise bookings (where available)",
      "Adventure activities & water sports",
      "Visa & passport assistance",
      "Travel insurance (if required)",
      "Complete travel guidance before & during trip",
    ],
    images: [
      "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1502920514313-52581002a659?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1488085061387-422e29b40080?auto=format&fit=crop&w=800&q=80",
    ],
    destinations: ["Bali", "Thailand", "Vietnam", "Dubai", "Maldives", "Singapore", "Malaysia", "Kashmir", "Kerala", "Goa", "Andaman", "Himachal Pradesh", "Uttarakhand", "Rajasthan", "Leh-Ladakh", "Northeast India"],
    cta: "Ready for your dream trip? Share your destination, dates, travellers and budget — we'll craft the perfect package for you.",
  },
  {
    slug: "hotel-booking",
    title: "Hotel Booking",
    subtitle: "Comfortable stays at the best rates, every time",
    hero: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1920&q=80",
    sections: [
      {
        heading: "Find Your Perfect Stay",
        body: "At The Get Set Go Holidays, we provide hotel booking services for both domestic and international destinations. Whether you are looking for a budget-friendly stay, a comfortable family hotel, a luxury resort, a honeymoon property, or a business hotel, we help you find the best accommodation according to your preferences and budget.",
      },
      {
        heading: "Handpicked with Care",
        body: "Our team carefully selects hotels based on location, guest reviews, amenities, and overall value to ensure a comfortable and hassle-free stay. We can arrange accommodations ranging from 3-star, 4-star, and 5-star hotels to boutique properties, villas, apartments, beach resorts, and mountain retreats.",
      },
    ],
    inclusions: [
      "Budget, deluxe, premium & luxury stays",
      "3-star, 4-star & 5-star hotels",
      "Boutique properties & villas",
      "Beach resorts & mountain retreats",
      "Early check-in & late check-out",
      "Family rooms & interconnected rooms",
      "Honeymoon & pool-view rooms",
      "Competitive rates & trusted accommodations",
    ],
    images: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
    ],
    cta: "Tell us your travel dates and preferences — we'll find the perfect hotel at the best price.",
  },
  {
    slug: "taxi-cab-services",
    title: "Taxi & Cab Services",
    subtitle: "Reliable rides, professional drivers, zero worries",
    hero: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1920&q=80",
    sections: [
      {
        heading: "Complete Ride Solutions",
        body: "We provide reliable and comfortable Taxi & Cab Services for all your travel needs. Whether you need a cab for airport transfers, railway station pick-up and drop, local sightseeing, outstation travel, one-way trips, round trips, or multi-city journeys, we can arrange it for you.",
      },
      {
        heading: "Long Road Trips",
        body: "If you're planning a long road trip and want to travel by car with a professional driver, we can provide well-maintained vehicles along with experienced chauffeurs to ensure a safe and comfortable journey.",
      },
    ],
    inclusions: [
      "Airport & railway station transfers",
      "Local sightseeing & outstation travel",
      "One-way, round trip & multi-city journeys",
      "Sedan cars (Swift Dzire, Honda Amaze, Hyundai Aura)",
      "SUVs (Ertiga, Kia Carens, Innova Crysta, Hycross)",
      "Premium & luxury cars (Camry, Mercedes, BMW, Audi)",
      "Tempo Traveller (9 to 26 seater)",
      "Mini-buses & luxury coaches for large groups",
      "Volvo & AC coaches for corporate tours",
      "Clean vehicles, professional drivers, on-time service",
    ],
    images: [
      "https://images.unsplash.com/photo-1525160354320-d8e92641c563?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1469285994282-454ceb49e63c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1566808907625-51f402658aba?auto=format&fit=crop&w=800&q=80",
    ],
    cta: "Book a cab for your next trip — city ride or road trip, we've got you covered.",
  },
  {
    slug: "flight-booking",
    title: "Flight Booking",
    subtitle: "Best airfares on domestic & international routes",
    hero: "https://images.unsplash.com/photo-1436491865332-7a61a109db05?auto=format&fit=crop&w=1920&q=80",
    sections: [
      {
        heading: "Fly Smarter, Not Harder",
        body: "We provide domestic and international flight booking services at competitive prices to make your travel planning easy and hassle-free. Whether you're travelling for a vacation, honeymoon, business trip, family holiday, or group tour, we help you find the best flight options based on your budget and preferred schedule.",
      },
      {
        heading: "Compare & Choose",
        body: "Our team compares multiple airlines to help you choose the most suitable flight with the best combination of price, comfort, and convenience. From booking your tickets to providing travel assistance, The Get Set Go Holidays ensures a smooth and stress-free flight booking experience.",
      },
    ],
    inclusions: [
      "Domestic flight bookings across India",
      "International flight bookings worldwide",
      "One-way, round-trip & multi-city bookings",
      "Economy, premium economy, business & first class",
      "Individual, family, corporate & group bookings",
      "Best available airfares & exclusive deals",
      "Baggage information & airline policy guidance",
      "Preferred seat selection (subject to availability)",
      "Special meal requests (where available)",
      "Rescheduling, date changes & cancellation assistance",
    ],
    images: [
      "https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1556388158-158f5f50145a?auto=format&fit=crop&w=800&q=80",
    ],
    cta: "Looking for the best flight deals? Share your route and dates — we'll find you the best fare.",
  },
  {
    slug: "complete-tour-planning",
    title: "Complete Tour Planning",
    subtitle: "One team, one platform, one seamless experience",
    hero: "https://images.unsplash.com/photo-1503220317375-aaad20136072?auto=format&fit=crop&w=1920&q=80",
    sections: [
      {
        heading: "Everything Under One Roof",
        body: "At The Get Set Go Holidays, we provide end-to-end tour-planning services, ensuring that every part of your trip is carefully planned and managed. Whether you're travelling within India or internationally, our team takes care of every detail so you can simply relax and enjoy your journey.",
      },
      {
        heading: "100% Customised",
        body: "We create 100% customised tour packages based on your destination, travel dates, budget, number of travellers, and personal preferences. Whether it's a family vacation, honeymoon, solo trip, group tour, corporate travel, religious tour, adventure holiday, or luxury getaway, we design the perfect itinerary for you.",
      },
      {
        heading: "From Booking to Homecoming",
        body: "Before your journey, we provide a detailed itinerary with all booking confirmations, hotel details, transportation information, sightseeing schedules, inclusions, exclusions, and important travel guidelines. From the moment you book with us until you return home, our team remains available to assist you at every step.",
      },
    ],
    inclusions: [
      "Flight booking & hotel reservation",
      "Private taxi, cab & airport transfers",
      "Intercity transportation",
      "Day-wise customized itinerary",
      "Sightseeing & attraction tickets",
      "Adventure activities & water sports",
      "Cruise & ferry bookings (where applicable)",
      "Meal planning as per package",
      "Visa & passport assistance",
      "Travel insurance & foreign exchange guidance",
      "24/7 travel assistance & customer support",
    ],
    images: [
      "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1495562569060-2eec2a3c3fb0?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80",
    ],
    cta: "Let us plan every detail of your trip. Share your vision — we'll make it happen.",
  },
  {
    slug: "passport-visa-services",
    title: "Passport & Visa Services",
    subtitle: "Hassle-free travel documentation guidance",
    hero: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1920&q=80",
    sections: [
      {
        heading: "Smooth Paperwork, Stress-Free Travel",
        body: "At The Get Set Go Holidays, we provide reliable passport & visa assistance to make your international travel smooth and stress-free. Whether you're applying for a new passport, renewing an existing one, or need a visa for your next destination, our experienced team will guide you through every step of the process.",
      },
      {
        heading: "Complete Documentation Support",
        body: "Our team helps you understand the document requirements, prepares you for the application process, and ensures that your paperwork is complete and accurate to minimise delays. We provide guidance for visa applications to a wide range of destinations worldwide.",
      },
    ],
    inclusions: [
      "New passport application assistance",
      "Passport renewal & re-issue support",
      "Passport correction & update guidance",
      "Tourist visa assistance",
      "Business visa assistance",
      "Family & group visa applications",
      "Complete documentation guidance",
      "Visa appointment scheduling support",
      "Cover letter & travel itinerary support",
      "Regular updates on application status",
    ],
    images: [
      "https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?auto=format&fit=crop&w=800&q=80",
    ],
    visaDestinations: [
      "Bali (Indonesia)", "Thailand", "Vietnam", "Dubai (UAE)",
      "Singapore", "Malaysia", "Europe (Schengen)", "United Kingdom",
      "United States", "Australia", "and many more",
    ],
    cta: "Planning an international trip? Let us handle the paperwork while you plan the fun.",
  },
  {
    slug: "honeymoon-group-tours",
    title: "Honeymoon & Group Tours",
    subtitle: "Romantic escapes & unforgettable group adventures",
    hero: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1920&q=80",
    sections: [
      {
        heading: "Honeymoon Packages",
        body: "Your honeymoon is one of the most special journeys of your life, and we make it truly unforgettable. We offer customised honeymoon packages with carefully selected romantic destinations, comfortable stays, and personalised experiences. Popular honeymoon destinations include Bali, Maldives, Thailand, Dubai, Kashmir, Kerala, Goa, Andaman, Himachal Pradesh, Vietnam, and many more.",
      },
      {
        heading: "Group Tours",
        body: "Travelling with a group becomes more enjoyable when everything is well planned. Whether it's a family reunion, friends' trip, corporate outing, college tour, school excursion, pilgrimage, or special interest group, we take care of every detail so everyone can enjoy the journey without any hassle.",
      },
    ],
    inclusions: [
      "Romantic hotel & resort stays",
      "Candlelight dinner arrangements",
      "Honeymoon room decoration (subject to availability)",
      "Private airport transfers & local transportation",
      "Couple-friendly activities & sightseeing",
      "Comfortable transportation & coach arrangements",
      "Group hotel bookings & meal arrangements",
      "Entry tickets & adventure activities",
      "Professional tour coordination (on request)",
      "Customized day-wise itinerary for groups",
    ],
    images: [
      "/images/packages/honeymoon-group-tours/darren-lawrence-EpeNGhitrlc-unsplash.jpg",
      "/images/packages/honeymoon-group-tours/khamkeo-OcxlTBbb6SY-unsplash.jpg",
      "/images/packages/honeymoon-group-tours/zidhan-ibrahim-2zykp7xLb1Q-unsplash.jpg",
    ],
    honeymoonHeroSections: [
      {
        heading: "Begin Your Forever Journey",
        body: "Start your married life with a beautiful escape designed just for you. Enjoy peaceful moments, romantic stays, and special experiences that bring you closer while creating unforgettable memories together.",
      },
      {
        heading: "Romance in Every Moment",
        body: "From candle light dinners to scenic views and cozy stays, every detail of your honeymoon is crafted to add love, comfort, and a touch of magic to your journey.",
      },
      {
        heading: "Create Memories for a Lifetime",
        body: "Celebrate your love with unique experiences, private time, and breathtaking destinations that make your honeymoon truly special and unforgettable.",
      },
    ],
    honeymoonPackages: [
      {
        title: "Our Honeymoon Packages",
        duration: "3N / 4D Stay",
        includes: "Candle Light Dinner | Local Sightseeing",
        price: "₹19,999 / Person",
        image: "/images/packages/honeymoon-group-tours/darren-lawrence-EpeNGhitrlc-unsplash.jpg",
      },
      {
        title: "Premium Honeymoon Experience",
        duration: "4N / 5D Stay",
        includes: "Private Transfers | Candle Light Dinner | Sightseeing",
        price: "₹29,999 / Person",
        image: "/images/packages/honeymoon-group-tours/khamkeo-OcxlTBbb6SY-unsplash.jpg",
      },
    ],
    honeymoonReasons: [
      "Romantic stays with beautiful views & ambience",
      "Special surprises like candle light dinners & decorations",
      "Privacy, comfort & personalized experiences",
      "Perfect for creating lifelong memories together",
    ],
    popularDestinations: {
      honeymoon: ["Bali", "Maldives", "Thailand", "Dubai", "Kashmir", "Kerala", "Goa", "Andaman", "Himachal Pradesh", "Vietnam"],
      group: ["Rajasthan", "Kerala", "Goa", "Himachal", "Uttarakhand", "Thailand", "Vietnam", "Dubai"],
    },
    cta: "Planning a honeymoon or group trip? Tell us your vision and we'll create the perfect itinerary.",
  },
  {
    slug: "adventure-riders-tours",
    title: "Adventure & Riders Tours",
    subtitle: "High-energy trips, road adventures & thrill-seeking escapes",
    hero: "/images/packages/adventure-riders-tours/nandu-vasudevan-qEXHAjgpjJU-unsplash.jpg",
    sections: [
      {
        heading: "Built for Thrill-Seekers",
        body: "If you're travelling with friends or fellow adventure lovers, we'll include exciting activities, nightlife, and adventure experiences that get your heart racing. From river rafting and trekking to bungee jumping and water sports, we design high-energy itineraries that match your adrenaline levels.",
      },
      {
        heading: "Rider-Friendly Road Trips",
        body: "For rider groups and biking enthusiasts, we organise epic road trips across India's most scenic routes — Leh-Ladakh, Spiti Valley, Kashmir to Kanyakumari, and more. We handle route planning, accommodations, mechanical backup, and support vehicles so you can focus on the ride. Whether you're on two wheels or four, we make sure your journey is as thrilling as the destination.",
      },
    ],
    inclusions: [
      "River rafting, trekking & bungee jumping",
      "Water sports & scuba diving",
      "Rider-friendly road trip planning",
      "Route mapping & support vehicle arrangement",
      "Camping & bonfire experiences",
      "Hotel stays & guesthouse bookings",
      "Adventure activity permits & guides",
      "Bike/car rental assistance",
      "Medical & travel insurance",
      "24/7 support during your trip",
    ],
    images: [
      "/images/packages/adventure-riders-tours/johanneke-kroesbergen-kamps-CvOLyQRE5vE-unsplash.jpg",
      "/images/packages/adventure-riders-tours/nitin-mishra-E7du69cRMKg-unsplash.jpg",
      "/images/packages/adventure-riders-tours/nandu-vasudevan-qEXHAjgpjJU-unsplash.jpg",
    ],
    destinations: ["Manali", "Kashmir", "Shimla", "Leh-Ladakh", "Spiti Valley", "Rishikesh", "Goa", "Kerala", "Northeast India", "Switzerland"],
    cta: "Ready for your next adventure? Tell us your dream destination and we'll plan an unforgettable trip.",
  },
  {
    slug: "family-vacations",
    title: "Family Vacations",
    subtitle: "Safe, fun & memorable holidays for every generation",
    hero: "/images/packages/family-vacations/jochen-van-wylick-ex0pl-zo7NM-unsplash.jpg",
    sections: [
      {
        heading: "Travel Together, Stress-Free",
        body: "We believe family holidays should be about creating memories, not managing logistics. If you're travelling with your family, we'll ensure you get comfortable hotels, safe transportation, and a relaxed itinerary that suits every generation — from grandparents to toddlers.",
      },
      {
        heading: "Perfectly Balanced Itineraries",
        body: "Our family vacation packages are designed with the right mix of sightseeing, leisure, and fun activities for all age groups. We include child-friendly attractions, safe transportation, family rooms, and enough downtime so nobody feels rushed. From beach resorts to hill stations, we plan everything so you can focus on spending quality time with your loved ones.",
      },
    ],
    inclusions: [
      "Family-friendly hotels with interconnected rooms",
      "Safe & comfortable transportation",
      "Child-friendly sightseeing & activities",
      "Balanced itineraries with leisure time",
      "Airport & railway station transfers",
      "Meal plans suited for all ages",
      "Adventure activities for older kids & adults",
      "Travel insurance for the whole family",
      "24/7 support during your trip",
    ],
    images: [
      "/images/packages/family-vacations/dylan-nolte-HNXi5znlb8U-unsplash.jpg",
      "/images/packages/family-vacations/natalya-zaritskaya-SIOdjcYotms-unsplash.jpg",
      "/images/packages/family-vacations/timon-studler-BIk2ANMmNz4-unsplash.jpg",
    ],
    destinations: ["Goa", "Kerala", "Rajasthan", "Himachal Pradesh", "Uttarakhand", "Dubai", "Thailand", "Singapore", "Malaysia", "Maldives", "Bali", "Andaman"],
    cta: "Planning a family getaway? Tell us your destination and dates — we'll create the perfect trip for every generation.",
  },
  {
    slug: "corporate-tours",
    title: "Corporate Tours",
    subtitle: "Professional travel management for teams & businesses",
    hero: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1920&q=80",
    sections: [
      {
        heading: "Seamless Corporate Travel",
        body: "At The Get Set Go Holidays, we specialize in organizing professionally planned Corporate Tours for companies, organizations, startups, educational institutions, and business teams. Whether you're planning an employee outing, team-building retreat, business conference, incentive trip, dealer meet, client event, or an annual corporate getaway, we provide complete travel management tailored to your organisation's needs.",
      },
      {
        heading: "Any Team Size, Any Occasion",
        body: "Whether your team consists of 10 or 500+ participants, we ensure seamless planning and execution with attention to every detail. From travel arrangements and accommodation to transportation, event coordination, and leisure activities, our experienced team manages everything so your employees and guests can focus on the purpose of the trip.",
      },
    ],
    inclusions: [
      "Domestic & international flight bookings",
      "Hotel & resort reservations",
      "Airport transfers & local transportation",
      "Tempo traveller, mini bus & luxury coach arrangements",
      "Customized corporate itineraries",
      "Conference hall & meeting venue bookings",
      "Meal planning & gala dinner arrangements",
      "Team building activities & adventure experiences",
      "Sightseeing & entertainment planning",
      "Visa & passport assistance for international tours",
      "Travel insurance (on request)",
      "Dedicated tour coordinator & 24/7 support",
    ],
    images: [
      "/images/packages/corporate-tour/ash-gerlach-6fF-Ojxov6o-unsplash.jpg",
      "/images/packages/corporate-tour/duy-pham-Cecb0_8Hx-o-unsplash.jpg",
      "/images/packages/corporate-tour/luca-bravo-_WiRAWxAhtg-unsplash.jpg",
    ],
    corporateTypes: [
      "Employee Reward & Incentive Trips",
      "Team Outings & Offsites",
      "Annual Company Retreats",
      "Conferences & Business Meetings",
      "Dealer & Distributor Meets",
      "Client Engagement Events",
      "Training & Workshops",
      "Educational & Industrial Visits",
    ],
    cta: "Planning a corporate trip? Share your requirements and we'll design a seamless travel experience.",
  },
];

export function getPackageDetail(slug) {
  return packageDetails.find((p) => p.slug === slug);
}

export const packageSlugs = packageDetails.map((p) => p.slug);
