export const servicesData = [
  {
    slug: "customized-tour-packages",
    name: "Customized Tour Packages",
    icon: "Map",
    subtitle: "Tailor-made holidays crafted around your dreams",
    heroImage: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=1920&q=80",
    content: [
      {
        heading: "Your Trip, Your Way",
        body: "We believe every traveler has different preferences, which is why we don't just sell fixed packages — we create <strong>100% customized tour packages</strong> according to your needs, budget, and travel style. Whether you're planning a family vacation, a honeymoon trip, a solo adventure, a group tour with friends, a corporate trip, a religious tour, or a weekend getaway, our team will plan everything for you from start to finish.",
      },
      {
        heading: "How It Works",
        body: "You just need to tell us <strong>where you want to go</strong>, your travel dates, how many people are travelling, your approximate budget, and any special preferences you have. Based on that, we'll prepare a <strong>personalized itinerary</strong> that suits you perfectly. Our packages include almost everything required for a smooth and stress-free journey.",
      },
      {
        heading: "What We Arrange",
        body: "We arrange domestic and international flight tickets, hotel bookings, airport and railway station transfers, private cabs, sightseeing tours, breakfast and other meals (as per the package), cruise bookings (where available), adventure activities, visa assistance, passport assistance, travel insurance (if required), and complete travel guidance before and during your trip.",
      },
      {
        heading: "Who We Cater To",
        body: "If you're travelling with your family, we'll ensure you get comfortable hotels, safe transportation, and a relaxed itinerary. If you're travelling with friends, we'll include exciting activities, nightlife, and adventure experiences. For honeymoon couples, we can arrange romantic hotel decorations, candlelight dinners, private transfers, and special honeymoon inclusions. If you're a solo traveller, we'll help you plan a safe and comfortable trip. We also organize group departures where you can travel with like-minded people.",
      },
      {
        heading: "Transparent Pricing",
        body: "Before you confirm your booking, we'll share a <strong>detailed day-wise itinerary</strong> along with hotel options, sightseeing details, package inclusions, exclusions, and pricing, so you know exactly what you're getting. We believe in transparent pricing with no hidden charges, and our team remains available to assist you before, during, and even after your trip.",
      },
    ],
    features: [
      { title: "Personalized Itinerary", icon: "Compass" },
      { title: "Budget Friendly", icon: "Wallet" },
      { title: "Domestic Tours", icon: "Map" },
      { title: "International Tours", icon: "Globe" },
      { title: "Luxury Packages", icon: "Gem" },
      { title: "Group Packages", icon: "Users" },
      { title: "Honeymoon Packages", icon: "Heart" },
      { title: "Family Tours", icon: "Briefcase" },
    ],
    included: [
      "Flight Tickets (Domestic & International)",
      "Hotel Accommodation",
      "Airport & Railway Transfers",
      "Private Cabs & Sightseeing",
      "Breakfast & Meals (as per package)",
      "Cruise Bookings (where available)",
      "Adventure Activities",
      "Visa & Passport Assistance",
      "Travel Insurance (on request)",
      "24/7 Travel Support",
    ],
    whyChooseUs: [
      { title: "Experienced Team", desc: "Years of travel expertise ensuring smooth trips.", icon: "ShieldCheck" },
      { title: "Transparent Pricing", desc: "No hidden charges, clear pricing from the start.", icon: "Eye" },
      { title: "No Hidden Charges", desc: "What you see is what you pay.", icon: "CheckCircle" },
      { title: "24×7 Support", desc: "We're here for you anytime, anywhere.", icon: "Headphones" },
      { title: "Trusted Hotels", desc: "Handpicked accommodations for every budget.", icon: "Hotel" },
      { title: "Best Deals", desc: "Competitive prices without compromising quality.", icon: "Tag" },
      { title: "Personalized Service", desc: "Every trip is designed uniquely for you.", icon: "Heart" },
      { title: "Safe Travel", desc: "Your safety is our top priority.", icon: "Shield" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1502920514313-52581002a659?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1488085061387-422e29b40080?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503220317375-aaad20136072?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1495562569060-2eec2a3c3fb0?auto=format&fit=crop&w=800&q=80",
    ],
    destinations: [
      { name: "Bali", image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80" },
      { name: "Thailand", image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=600&q=80" },
      { name: "Vietnam", image: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=600&q=80" },
      { name: "Dubai", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80" },
      { name: "Maldives", image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=600&q=80" },
      { name: "Singapore", image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=600&q=80" },
      { name: "Kerala", image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=600&q=80" },
      { name: "Kashmir", image: "https://images.unsplash.com/photo-1597434155806-9122caf0896c?auto=format&fit=crop&w=600&q=80" },
      { name: "Goa", image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f9?auto=format&fit=crop&w=600&q=80" },
      { name: "Rajasthan", image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80" },
    ],
    faqs: [
      { q: "How do I customize my tour package?", a: "Simply share your destination, travel dates, number of travellers, budget, and preferences with us. Our team will create a personalized itinerary within 24-48 hours." },
      { q: "Do you offer both domestic and international packages?", a: "Yes, we offer customized packages for destinations across India and more than 20 international countries including Bali, Thailand, Dubai, Maldives, and many more." },
      { q: "Can I make changes to the itinerary after booking?", a: "Yes, we allow modifications to your itinerary based on availability. Additional charges may apply depending on the changes requested." },
      { q: "Is travel insurance included in the package?", a: "Travel insurance can be added on request. We recommend it for international trips and adventure activities." },
      { q: "How do I make a booking?", a: "You can reach us via phone, WhatsApp, email, or our contact form. We'll discuss your requirements, share a detailed quote, and proceed with the booking upon confirmation." },
      { q: "What payment methods do you accept?", a: "We accept bank transfers, UPI, credit/debit cards, and other digital payment methods. A partial advance is required to confirm the booking." },
      { q: "Do you provide visa assistance?", a: "Yes, we provide complete visa guidance and documentation support for international destinations." },
      { q: "Can I get a refund if I cancel?", a: "Cancellation policies vary depending on the package and service providers. We'll clearly communicate the cancellation policy before you confirm." },
      { q: "Do you offer group discounts?", a: "Yes, we offer special pricing for group bookings of 5 or more travellers." },
      { q: "How far in advance should I book?", a: "We recommend booking at least 2-4 weeks in advance for domestic trips and 4-6 weeks for international trips to get the best rates." },
    ],
  },
  {
    slug: "hotel-booking",
    name: "Hotel Booking",
    icon: "Hotel",
    subtitle: "Comfortable stays at the best rates, every time",
    heroImage: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1920&q=80",
    content: [
      {
        heading: "Find Your Perfect Stay",
        body: "At The Get Set Go Holidays, we provide <strong>hotel booking services</strong> for both domestic and international destinations. Whether you are looking for a budget-friendly stay, a comfortable family hotel, a luxury resort, a honeymoon property, or a business hotel, we help you find the best accommodation according to your preferences and budget.",
      },
      {
        heading: "Handpicked with Care",
        body: "Our team carefully selects hotels based on location, guest reviews, amenities, and overall value to ensure a comfortable and hassle-free stay. We can arrange accommodations ranging from <strong>3-star, 4-star, and 5-star hotels</strong> to boutique properties, villas, apartments, beach resorts, and mountain retreats.",
      },
      {
        heading: "Special Requests",
        body: "We also assist with special requirements such as early check-in, late check-out, family rooms, interconnected rooms, honeymoon arrangements, pool-view rooms, and other personalised requests whenever available. Whether you are travelling solo, with family, friends, or on a corporate trip, we ensure that your stay is comfortable, convenient, and suited to your travel needs.",
      },
      {
        heading: "Competitive Rates",
        body: "With our hotel booking service, you can enjoy <strong>competitive rates</strong>, trusted accommodations, and complete support from our travel experts, allowing you to focus on enjoying your journey while we take care of your stay.",
      },
    ],
    features: [
      { title: "Budget Hotels", icon: "Wallet" },
      { title: "3-Star Hotels", icon: "Star" },
      { title: "4-Star Hotels", icon: "Star" },
      { title: "5-Star Hotels", icon: "Star" },
      { title: "Luxury Resorts", icon: "Gem" },
      { title: "Boutique Stays", icon: "Building2" },
      { title: "Beach Resorts", icon: "Umbrella" },
      { title: "Mountain Retreats", icon: "Mountain" },
    ],
    included: [
      "Verified Hotel Bookings",
      "Best Available Rates",
      "Early Check-in / Late Check-out",
      "Free Cancellation Options",
      "Room Upgrades (subject to availability)",
      "Special Requests Handling",
      "Honeymoon Arrangements",
      "Family & Interconnected Rooms",
      "24/7 Customer Support",
      "Travel Expert Assistance",
    ],
    whyChooseUs: [
      { title: "Trusted Hotels", desc: "Only verified and guest-reviewed properties.", icon: "ShieldCheck" },
      { title: "Best Price Guarantee", desc: "We match or beat any online rate.", icon: "Tag" },
      { title: "No Hidden Charges", desc: "Transparent pricing from booking to checkout.", icon: "CheckCircle" },
      { title: "Wide Selection", desc: "From budget stays to luxury resorts worldwide.", icon: "Building2" },
      { title: "Instant Confirmation", desc: "Get your booking confirmed in minutes.", icon: "Clock" },
      { title: "Free Cancellation", desc: "Flexible booking options available.", icon: "RotateCcw" },
      { title: "Local Expertise", desc: "Recommendations based on real guest experiences.", icon: "Compass" },
      { title: "24/7 Support", desc: "Round-the-clock assistance for any issues.", icon: "Headphones" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1581078738028-20fea3e9db2d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1560200353-ce0a76b1d438?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    ],
    destinations: [
      { name: "Dubai", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80" },
      { name: "Bali", image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80" },
      { name: "Maldives", image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=600&q=80" },
      { name: "Thailand", image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=600&q=80" },
      { name: "Singapore", image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=600&q=80" },
      { name: "Kerala", image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=600&q=80" },
      { name: "Goa", image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f9?auto=format&fit=crop&w=600&q=80" },
      { name: "Rajasthan", image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80" },
    ],
    faqs: [
      { q: "What types of hotels can you book?", a: "We book everything from budget hotels and 3-star properties to 5-star luxury resorts, boutique villas, apartments, and mountain retreats." },
      { q: "Do you offer better rates than online portals?", a: "Yes, we have exclusive partnerships with hotels and often offer rates that match or beat online booking portals." },
      { q: "Can I request early check-in or late check-out?", a: "Yes, we note your preferences and request the hotel. These are subject to availability and may involve additional charges." },
      { q: "Is free cancellation available?", a: "Many hotels offer free cancellation within a specified period. We'll inform you of the cancellation policy before booking." },
      { q: "Do you book hotels for group travel?", a: "Yes, we specialize in group hotel bookings and can arrange interconnected rooms, bulk discounts, and dedicated floors for groups." },
      { q: "Can you arrange honeymoon specials?", a: "Absolutely! We can arrange room decorations, cake, flowers, and other romantic surprises subject to hotel availability." },
      { q: "How do I know the hotel is trustworthy?", a: "We only recommend hotels with proven guest reviews, verified ratings, and our own team's quality checks." },
      { q: "What if I have issues at the hotel?", a: "Our team is available 24/7 to assist with any issues during your stay, from room changes to service complaints." },
    ],
  },
  {
    slug: "taxi-cab-services",
    name: "Taxi & Cab Services",
    icon: "Car",
    subtitle: "Reliable rides, professional drivers, zero worries",
    heroImage: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1920&q=80",
    content: [
      {
        heading: "Complete Ride Solutions",
        body: "We provide reliable and comfortable <strong>Taxi & Cab Services</strong> for all your travel needs. Whether you need a cab for airport transfers, railway station pick-up and drop, local sightseeing, outstation travel, one-way trips, round trips, or multi-city journeys, we can arrange it for you.",
      },
      {
        heading: "Long Road Trips",
        body: "If you're planning a long road trip and want to travel by car with a professional driver, we can provide <strong>well-maintained vehicles</strong> along with experienced chauffeurs to ensure a safe and comfortable journey.",
      },
      {
        heading: "Wide Range of Vehicles",
        body: "We offer a wide range of vehicles based on your group size and budget including Sedan Cars (Swift Dzire, Honda Amaze, Hyundai Aura), SUVs (Ertiga, Kia Carens, Toyota Innova Crysta, Innova Hycross), Premium & Luxury Cars (Toyota Camry, Mercedes-Benz, BMW, Audi), Tempo Traveller (9, 12, 16, 17, 20 & 26 Seater), Mini-buses & Luxury Coaches for large groups, and Volvo & AC Coaches for corporate tours and group departures.",
      },
      {
        heading: "Our Commitment",
        body: "Whether you're travelling solo, with your family, friends, or a large group, we ensure <strong>clean vehicles, professional drivers, on-time service, and competitive pricing</strong>. From short city rides to long-distance road trips across India, The Get Set Go Holidays provides complete transportation solutions to make your journey safe, convenient, and hassle-free.",
      },
    ],
    features: [
      { title: "Airport Transfers", icon: "Plane" },
      { title: "Local Sightseeing", icon: "Route" },
      { title: "Outstation Travel", icon: "MapPinned" },
      { title: "One-Way Trips", icon: "ArrowRight" },
      { title: "Round Trips", icon: "RefreshCcw" },
      { title: "Multi-City Tours", icon: "Map" },
      { title: "Corporate Travel", icon: "Briefcase" },
      { title: "Group Transport", icon: "Bus" },
    ],
    included: [
      "Clean & Sanitized Vehicles",
      "Professional Drivers",
      "On-Time Pickup & Drop",
      "Airport & Railway Transfers",
      "Sightseeing Tours",
      "Intercity & Outstation Trips",
      "Fuel, Toll & Parking Included",
      "GPS Tracking",
      "24/7 Customer Support",
      "Competitive Pricing",
    ],
    whyChooseUs: [
      { title: "Professional Drivers", desc: "Experienced, courteous, and trained chauffeurs.", icon: "ShieldCheck" },
      { title: "Clean Vehicles", desc: "Well-maintained and sanitized cars for every ride.", icon: "Sparkles" },
      { title: "On-Time Service", desc: "Punctuality is our promise.", icon: "Clock" },
      { title: "Best Rates", desc: "Competitive pricing with no hidden charges.", icon: "Tag" },
      { title: "GPS Tracked", desc: "Real-time tracking for safety and convenience.", icon: "Map" },
      { title: "Wide Fleet", desc: "Sedans, SUVs, Tempo Travellers & Luxury Cars.", icon: "Car" },
      { title: "24/7 Availability", desc: "Book anytime, ride anytime.", icon: "Headphones" },
      { title: "Safe Travel", desc: "Your safety is our top priority.", icon: "Shield" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1525160354320-d8e92641c563?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1469285994282-454ceb49e63c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1566808907625-51f402658aba?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1519003722824-194d4455a60c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
    ],
    destinations: [
      { name: "Delhi", image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=600&q=80" },
      { name: "Mumbai", image: "https://images.unsplash.com/photo-1529253355930-ddbe423a2ac7?auto=format&fit=crop&w=600&q=80" },
      { name: "Jaipur", image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=600&q=80" },
      { name: "Goa", image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f9?auto=format&fit=crop&w=600&q=80" },
      { name: "Manali", image: "https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?auto=format&fit=crop&w=600&q=80" },
      { name: "Rishikesh", image: "https://images.unsplash.com/photo-1566766184873-21e085c3f361?auto=format&fit=crop&w=600&q=80" },
      { name: "Kerala", image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=600&q=80" },
      { name: "Uttarakhand", image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=600&q=80" },
    ],
    faqs: [
      { q: "What types of vehicles do you offer?", a: "We offer sedans, SUVs, premium luxury cars, Tempo Travellers (9-26 seater), mini-buses, and luxury coaches." },
      { q: "Can I book a cab for outstation trips?", a: "Yes, we provide one-way, round trip, and multi-city outstation travel services with experienced drivers." },
      { q: "Are your drivers professional and licensed?", a: "All our drivers are verified, licensed, and trained for customer service and safe driving." },
      { q: "Do you provide airport transfer services?", a: "Yes, we offer reliable airport pickup and drop services with flight tracking for punctuality." },
      { q: "Is there a waiting charge?", a: "Reasonable waiting time is included. Additional charges may apply beyond the agreed waiting period." },
      { q: "Can I book a cab for a full-day sightseeing tour?", a: "Absolutely! We offer full-day and half-day sightseeing packages with flexible itineraries." },
      { q: "Do you provide child seats?", a: "Child seats can be arranged on request. Please inform us at the time of booking." },
      { q: "How do I pay for the cab service?", a: "You can pay via cash, UPI, bank transfer, or card. Advance payment is required for outstation bookings." },
    ],
  },
  {
    slug: "flight-booking",
    name: "Flight Booking",
    icon: "Plane",
    subtitle: "Best airfares on domestic & international routes",
    heroImage: "https://images.unsplash.com/photo-1436491865332-7a61a109db05?auto=format&fit=crop&w=1920&q=80",
    content: [
      {
        heading: "Fly Smarter, Not Harder",
        body: "We provide <strong>domestic and international flight booking</strong> services at competitive prices to make your travel planning easy and hassle-free. Whether you're travelling for a vacation, honeymoon, business trip, family holiday, or group tour, we help you find the best flight options based on your budget and preferred schedule.",
      },
      {
        heading: "Comprehensive Services",
        body: "Our flight booking services include Domestic Flight Bookings across India, International Flight Bookings to destinations worldwide, One-Way, Round-Trip & Multi-City Flight Bookings, Economy, Premium Economy, Business & First Class Tickets, Individual, Family, Corporate & Group Flight Bookings, Best Available Airfares and Exclusive Travel Deals.",
      },
      {
        heading: "Additional Assistance",
        body: "We also provide assistance with Baggage Information and Airline Policies, Preferred Seat Selection (subject to airline availability), Special Meal Requests (where available), Flight Rescheduling, Date Changes & Cancellation Assistance, and Travel Documentation Guidance for International Travel.",
      },
      {
        heading: "Compare & Choose",
        body: "Our team compares <strong>multiple airlines</strong> to help you choose the most suitable flight with the best combination of price, comfort, and convenience. From booking your tickets to providing travel assistance, The Get Set Go Holidays ensures a smooth and stress-free flight booking experience.",
      },
    ],
    features: [
      { title: "Domestic Flights", icon: "Plane" },
      { title: "International Flights", icon: "Globe" },
      { title: "One-Way Bookings", icon: "ArrowRight" },
      { title: "Round-Trip Bookings", icon: "RefreshCcw" },
      { title: "Multi-City Bookings", icon: "Route" },
      { title: "Business Class", icon: "Gem" },
      { title: "Group Bookings", icon: "Users" },
      { title: "Corporate Bookings", icon: "Briefcase" },
    ],
    included: [
      "Domestic & International Flight Booking",
      "Best Available Airfares",
      "One-Way / Round-Trip / Multi-City",
      "Economy, Premium Economy & Business Class",
      "Seat Selection Assistance",
      "Special Meal Requests",
      "Baggage Information Guidance",
      "Rescheduling & Cancellation Help",
      "Visa Documentation Guidance",
      "24/7 Booking Support",
    ],
    whyChooseUs: [
      { title: "Best Airfares", desc: "We compare across airlines for the best price.", icon: "Tag" },
      { title: "Easy Booking", desc: "Simple and quick booking process.", icon: "Clock" },
      { title: "Flexible Options", desc: "One-way, round-trip, multi-city available.", icon: "RefreshCcw" },
      { title: "24/7 Support", desc: "Assistance before, during, and after your flight.", icon: "Headphones" },
      { title: "Trusted Service", desc: "Reliable bookings with confirmed tickets.", icon: "ShieldCheck" },
      { title: "Group Discounts", desc: "Special fares for group and corporate bookings.", icon: "Users" },
      { title: "Seat Selection", desc: "Preferred seats arranged subject to availability.", icon: "Plane" },
      { title: "Cancellation Help", desc: "Guidance on rescheduling and refunds.", icon: "RotateCcw" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1542296332-2e4473faf563?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1556388158-158f5f50145a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1436491865332-7a61a109db05?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1436491865332-7a61a109db05?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
    ],
    faqs: [
      { q: "Do you book both domestic and international flights?", a: "Yes, we book flights for all domestic routes across India and international destinations worldwide." },
      { q: "Can I get cheaper rates than online portals?", a: "We compare multiple airlines to find the best fares and also have access to exclusive deals and discounts." },
      { q: "Do you help with flight cancellations or rescheduling?", a: "Yes, we assist with rescheduling, date changes, and cancellations as per the airline's policy." },
      { q: "Can I select my seat in advance?", a: "We can request preferred seating subject to airline availability at the time of booking." },
      { q: "Do you offer group flight bookings?", a: "Yes, we offer special fares for group bookings of 10 or more passengers." },
      { q: "What class options are available?", a: "We book Economy, Premium Economy, Business Class, and First Class tickets depending on the route." },
      { q: "Do you provide travel insurance with flights?", a: "Travel insurance can be added on request for both domestic and international flights." },
      { q: "How do I get my e-ticket?", a: "Your e-ticket and invoice will be sent to your email and WhatsApp immediately after booking confirmation." },
    ],
  },
  {
    slug: "complete-tour-planning",
    name: "Complete Tour Planning",
    icon: "ClipboardList",
    subtitle: "One team, one platform, one seamless experience",
    heroImage: "https://images.unsplash.com/photo-1503220317375-aaad20136072?auto=format&fit=crop&w=1920&q=80",
    content: [
      {
        heading: "Everything Under One Roof",
        body: "At The Get Set Go Holidays, we provide <strong>end-to-end tour-planning services</strong>, ensuring that every part of your trip is carefully planned and managed. Whether you're travelling within India or internationally, our team takes care of every detail so you can simply relax and enjoy your journey.",
      },
      {
        heading: "100% Customised Itineraries",
        body: "We create <strong>100% customised tour packages</strong> based on your destination, travel dates, budget, number of travellers, and personal preferences. Whether it's a family vacation, honeymoon, solo trip, group tour, corporate travel, religious tour, adventure holiday, or luxury getaway, we design the perfect itinerary for you.",
      },
      {
        heading: "What's Included",
        body: "Our complete tour planning service includes Flight Booking, Hotel & Resort Booking, Private Taxi, Cab & Airport Transfers, Intercity Transportation, Day-wise Customized Itinerary, Sightseeing & Attraction Tickets, Adventure Activities & Water Sports, Cruise & Ferry Bookings, Meal Planning, Visa & Passport Assistance, Travel Insurance, Foreign Exchange Guidance, and 24/7 Travel Assistance.",
      },
      {
        heading: "From Booking to Homecoming",
        body: "Before your journey, we provide a <strong>detailed itinerary</strong> with all booking confirmations, hotel details, transportation information, sightseeing schedules, inclusions, exclusions, and important travel guidelines. From the moment you book with us until you return home, our team remains available to assist you at every step.",
      },
    ],
    features: [
      { title: "Custom Itinerary", icon: "ClipboardList" },
      { title: "Flight Booking", icon: "Plane" },
      { title: "Hotel Reservation", icon: "Hotel" },
      { title: "Transport Arrangement", icon: "Car" },
      { title: "Sightseeing Planning", icon: "Map" },
      { title: "Visa Assistance", icon: "Passport" },
      { title: "Travel Insurance", icon: "Shield" },
      { title: "24/7 Support", icon: "Headphones" },
    ],
    included: [
      "Flight Booking & Hotel Reservation",
      "Private Taxi, Cab & Airport Transfers",
      "Intercity Transportation",
      "Day-wise Customized Itinerary",
      "Sightseeing & Attraction Tickets",
      "Adventure Activities & Water Sports",
      "Cruise & Ferry Bookings",
      "Meal Planning as per Package",
      "Visa & Passport Assistance",
      "24/7 Travel Assistance & Support",
    ],
    whyChooseUs: [
      { title: "End-to-End Service", desc: "Everything handled under one roof.", icon: "ClipboardList" },
      { title: "Expert Planning", desc: "Experienced team crafting perfect itineraries.", icon: "Compass" },
      { title: "Best Pricing", desc: "Competitive rates across all services.", icon: "Tag" },
      { title: "No Hidden Charges", desc: "Transparent pricing with full disclosure.", icon: "Eye" },
      { title: "Personalized Approach", desc: "Every trip designed uniquely for you.", icon: "Heart" },
      { title: "24/7 Support", desc: "Assistance before, during, and after your trip.", icon: "Headphones" },
      { title: "Trusted Partners", desc: "Verified hotels, airlines and transport providers.", icon: "ShieldCheck" },
      { title: "Stress-Free Travel", desc: "We handle everything while you enjoy.", icon: "Sparkles" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1495562569060-2eec2a3c3fb0?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503220317375-aaad20136072?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1488085061387-422e29b40080?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1502920514313-52581002a659?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80",
    ],
    destinations: [
      { name: "Bali", image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80" },
      { name: "Thailand", image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=600&q=80" },
      { name: "Dubai", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80" },
      { name: "Maldives", image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=600&q=80" },
      { name: "Kerala", image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=600&q=80" },
      { name: "Kashmir", image: "https://images.unsplash.com/photo-1597434155806-9122caf0896c?auto=format&fit=crop&w=600&q=80" },
      { name: "Goa", image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f9?auto=format&fit=crop&w=600&q=80" },
      { name: "Rajasthan", image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80" },
      { name: "Himachal", image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=600&q=80" },
      { name: "Vietnam", image: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=600&q=80" },
    ],
    faqs: [
      { q: "What does complete tour planning include?", a: "It includes flights, hotels, transfers, sightseeing, meals, activities, visa assistance, travel insurance, and 24/7 support." },
      { q: "Can I customize the itinerary?", a: "Yes, every itinerary is 100% customized based on your preferences, budget, and requirements." },
      { q: "How far in advance should I plan?", a: "We recommend 2-3 weeks for domestic trips and 4-6 weeks for international trips for the best arrangements." },
      { q: "Do you handle group tours?", a: "Yes, we specialize in group tours including family reunions, corporate outings, and friends' trips." },
      { q: "Is visa assistance included?", a: "Yes, we provide complete visa guidance and documentation support for international destinations." },
      { q: "What if I need to change my plan after booking?", a: "We allow modifications subject to availability. Additional charges may apply based on changes." },
      { q: "Do you provide travel insurance?", a: "Yes, travel insurance can be added to your package on request." },
      { q: "How do I get started?", a: "Simply share your destination, dates, number of travellers, and budget. We'll create a personalized plan within 24-48 hours." },
      { q: "What payment options are available?", a: "We accept bank transfers, UPI, cards, and digital wallets. An advance is required to confirm bookings." },
      { q: "Is there post-booking support?", a: "Yes, our team is available 24/7 before, during, and after your trip for any assistance." },
    ],
  },
  {
    slug: "passport-visa-services",
    name: "Passport & Visa Services",
    icon: "Passport",
    subtitle: "Hassle-free travel documentation guidance",
    heroImage: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=1920&q=80",
    content: [
      {
        heading: "Smooth Paperwork, Stress-Free Travel",
        body: "At The Get Set Go Holidays, we provide <strong>reliable passport & visa assistance</strong> to make your international travel smooth and stress-free. Whether you're applying for a new passport, renewing an existing one, or need a visa for your next destination, our experienced team will guide you through every step of the process.",
      },
      {
        heading: "Passport Services",
        body: "Our passport services include New Passport Application Assistance, Passport Renewal & Re-issue Support, and Passport Correction & Update Guidance. We help you with the entire application process, documentation, and tracking.",
      },
      {
        heading: "Visa Services",
        body: "Our visa services cover Tourist Visa Assistance, Business Visa Assistance, Family & Group Visa Applications, Complete Documentation Guidance, Visa Appointment Scheduling Support, Visa Application Form Assistance, Cover Letter & Travel Itinerary Support, and Regular Updates on Your Application Status.",
      },
      {
        heading: "Destinations We Cover",
        body: "We provide visa assistance for a wide range of destinations including Bali (Indonesia), Thailand, Vietnam, Dubai (UAE), Singapore, Malaysia, Europe (Schengen), the United Kingdom, the United States, Australia, and many other countries.",
      },
    ],
    features: [
      { title: "New Passport", icon: "Passport" },
      { title: "Passport Renewal", icon: "RefreshCcw" },
      { title: "Tourist Visa", icon: "Stamp" },
      { title: "Business Visa", icon: "Briefcase" },
      { title: "Family Visa", icon: "Users" },
      { title: "Schengen Visa", icon: "Globe" },
      { title: "Document Guidance", icon: "FileText" },
      { title: "Appointment Support", icon: "Calendar" },
    ],
    included: [
      "New Passport Application Assistance",
      "Passport Renewal & Re-issue Support",
      "Passport Correction & Update Guidance",
      "Tourist & Business Visa Assistance",
      "Family & Group Visa Applications",
      "Complete Documentation Guidance",
      "Visa Appointment Scheduling",
      "Cover Letter & Itinerary Support",
      "Application Status Updates",
      "Expert Consultation",
    ],
    whyChooseUs: [
      { title: "Expert Guidance", desc: "Experienced team handling your paperwork.", icon: "ShieldCheck" },
      { title: "Complete Support", desc: "From forms to follow-up, we handle it all.", icon: "ClipboardList" },
      { title: "Timely Updates", desc: "Regular status updates on your application.", icon: "Bell" },
      { title: "Document Check", desc: "Thorough review to avoid rejections.", icon: "Search" },
      { title: "Multiple Destinations", desc: "Visa assistance for 20+ countries.", icon: "Globe" },
      { title: "Fast Processing", desc: "We expedite wherever possible.", icon: "Clock" },
      { title: "Transparent Process", desc: "Clear guidance on fees and timelines.", icon: "Eye" },
      { title: "High Success Rate", desc: "Proven track record of approvals.", icon: "Award" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1559526324-593bc073d938?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1575505586567-535a1a2c1b5a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80",
    ],
    faqs: [
      { q: "What documents are needed for a passport application?", a: "You need proof of identity, address proof, date of birth proof, and passport-sized photographs. We guide you through the complete list." },
      { q: "How long does it take to get a passport?", a: "Normal processing takes 7-15 working days. Tatkaal (expedited) processing takes 2-5 working days." },
      { q: "Do you help with passport renewal?", a: "Yes, we assist with the entire passport renewal and re-issue process including form filling and appointment booking." },
      { q: "Which visas do you assist with?", a: "We assist with tourist, business, family, and group visas for Bali, Thailand, Vietnam, Dubai, Singapore, Malaysia, Europe (Schengen), UK, USA, Australia, and more." },
      { q: "Is visa guarantee provided?", a: "No, visa approval is at the discretion of the embassy. However, we ensure your application is complete and accurate to maximize approval chances." },
      { q: "How much do visa services cost?", a: "Costs vary by destination and visa type. We provide a detailed fee breakdown before you proceed." },
      { q: "Do you handle biometric appointments?", a: "Yes, we assist with appointment scheduling and guide you on the biometric process." },
      { q: "What if my visa is rejected?", a: "We analyze the rejection reason and guide you on reapplying with stronger documentation." },
    ],
  },
  {
    slug: "honeymoon-group-tours",
    name: "Honeymoon & Group Tours",
    icon: "Heart",
    subtitle: "Romantic escapes & unforgettable group adventures",
    heroImage: "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1920&q=80",
    content: [
      {
        heading: "Honeymoon Packages",
        body: "Your honeymoon is one of the <strong>most special journeys</strong> of your life, and we make it truly unforgettable. We offer customised honeymoon packages with carefully selected romantic destinations, comfortable stays, and personalised experiences.",
      },
      {
        heading: "Honeymoon Inclusions",
        body: "Our honeymoon packages include Romantic Hotel & Resort Stays, Candlelight Dinner Arrangements, Honeymoon Room Decoration, Private Airport Transfers & Local Transportation, Sightseeing & Romantic Experiences, Couple-Friendly Activities, Flight Booking Assistance, Visa Assistance for International Destinations, and Fully Customized Itineraries.",
      },
      {
        heading: "Group Tours",
        body: "Travelling with a group becomes more enjoyable when everything is well planned. Whether it's a family reunion, friends' trip, corporate outing, college tour, school excursion, pilgrimage, or special interest group, we take care of every detail so everyone can enjoy the journey without any hassle.",
      },
      {
        heading: "Group Tour Services",
        body: "Our group tour services include Comfortable Transportation & Coach Arrangements, Group Hotel Bookings, Meal Arrangements, Sightseeing & Activity Planning, Entry Tickets & Adventure Activities, Professional Tour Coordination, Group Flight Bookings, Airport & Local Transfers, Customized Day-wise Itinerary, and Dedicated Support Throughout the Tour.",
      },
    ],
    features: [
      { title: "Honeymoon Packages", icon: "Heart" },
      { title: "Group Tours", icon: "Users" },
      { title: "Romantic Stays", icon: "Hotel" },
      { title: "Candlelight Dinners", icon: "Sparkles" },
      { title: "Adventure Activities", icon: "Mountain" },
      { title: "Sightseeing Tours", icon: "Map" },
      { title: "Visa Assistance", icon: "Passport" },
      { title: "Custom Itineraries", icon: "ClipboardList" },
    ],
    included: [
      "Romantic Hotel & Resort Stays",
      "Candlelight Dinner Arrangements",
      "Honeymoon Room Decoration",
      "Private Airport Transfers",
      "Couple-Friendly Activities",
      "Comfortable Group Transport",
      "Group Hotel Bookings & Meals",
      "Entry Tickets & Activities",
      "Professional Tour Coordination",
      "Dedicated Support Throughout",
    ],
    whyChooseUs: [
      { title: "Romantic Experiences", desc: "Special touches for your dream honeymoon.", icon: "Heart" },
      { title: "Group Expertise", desc: "Years of experience organizing group travel.", icon: "Users" },
      { title: "Customized Planning", desc: "Tailored itineraries for every couple or group.", icon: "ClipboardList" },
      { title: "Best Destinations", desc: "Curated selection of romantic and group destinations.", icon: "Globe" },
      { title: "Stress-Free Travel", desc: "We handle all logistics so you can relax.", icon: "Sparkles" },
      { title: "24/7 Support", desc: "Assistance whenever you need it.", icon: "Headphones" },
      { title: "Expert Guides", desc: "Experienced tour coordinators for groups.", icon: "Compass" },
      { title: "Great Value", desc: "Competitive pricing without compromising quality.", icon: "Tag" },
    ],
    gallery: [
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1566195992011-5f6b21e9aa6b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1530973428-5c2f2eb0b4b5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?auto=format&fit=crop&w=800&q=80",
    ],
    destinations: [
      { name: "Bali", image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80" },
      { name: "Maldives", image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=600&q=80" },
      { name: "Thailand", image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=600&q=80" },
      { name: "Dubai", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80" },
      { name: "Kashmir", image: "https://images.unsplash.com/photo-1597434155806-9122caf0896c?auto=format&fit=crop&w=600&q=80" },
      { name: "Kerala", image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=600&q=80" },
      { name: "Goa", image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f9?auto=format&fit=crop&w=600&q=80" },
      { name: "Himachal", image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=600&q=80" },
      { name: "Vietnam", image: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=600&q=80" },
      { name: "Andaman", image: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=600&q=80" },
    ],
    faqs: [
      { q: "What's included in honeymoon packages?", a: "Romantic hotel stays, candlelight dinners, room decorations, private transfers, couple activities, and customized itineraries." },
      { q: "Can you plan a surprise for my partner?", a: "Absolutely! We can arrange room decorations, cake, flowers, candlelight dinners, and other surprises." },
      { q: "What are the best honeymoon destinations?", a: "Bali, Maldives, Thailand, Dubai, Kashmir, Kerala, Goa, Andaman, and Vietnam are our most popular choices." },
      { q: "Do you handle group tours for large parties?", a: "Yes, we handle groups of all sizes with dedicated tour coordinators and customized logistics." },
      { q: "Can I combine a honeymoon with a group trip?", a: "We can create custom itineraries that combine private couple time with group activities." },
      { q: "What transport options are available for groups?", a: "We arrange Tempo Travellers, mini-buses, luxury coaches, and private cabs based on group size." },
      { q: "Do you assist with honeymoon visa applications?", a: "Yes, we provide visa assistance for international honeymoon destinations." },
      { q: "Is travel insurance included?", a: "Travel insurance can be added to both honeymoon and group packages on request." },
      { q: "Can I customize the group tour itinerary?", a: "Yes, every group tour itinerary is 100% customizable based on your preferences." },
      { q: "How do I book a honeymoon or group package?", a: "Contact us with your destination, dates, and budget. We'll share a detailed itinerary within 24-48 hours." },
    ],
  },
  {
    slug: "corporate-tours",
    name: "Corporate Tours",
    icon: "Briefcase",
    subtitle: "Professional travel management for teams & businesses",
    heroImage: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1920&q=80",
    content: [
      {
        heading: "Seamless Corporate Travel",
        body: "At The Get Set Go Holidays, we specialize in organizing professionally planned <strong>Corporate Tours</strong> for companies, organizations, startups, educational institutions, and business teams. Whether you're planning an employee outing, team-building retreat, business conference, incentive trip, dealer meet, client event, or an annual corporate getaway, we provide complete travel management tailored to your organisation's needs.",
      },
      {
        heading: "Our Services",
        body: "Our corporate tour services include Domestic & International Flight Bookings, Hotel & Resort Reservations, Airport Transfers & Local Transportation, Tempo Traveller, Mini Bus & Luxury Coach Arrangements, Customized Corporate Itineraries, Conference Hall & Meeting Venue Bookings, Meal Planning & Gala Dinner Arrangements, Team Building Activities & Adventure Experiences, Sightseeing & Entertainment Planning, Visa & Passport Assistance for International Tours, Travel Insurance (on request), Dedicated Tour Coordinator, and 24/7 Travel Support.",
      },
      {
        heading: "Any Team Size",
        body: "Whether your team consists of 10 or 500+ participants, we ensure <strong>seamless planning and execution</strong> with attention to every detail. From travel arrangements and accommodation to transportation, event coordination, and leisure activities, our experienced team manages everything so your employees and guests can focus on the purpose of the trip.",
      },
      {
        heading: "Occasions We Cover",
        body: "We organise corporate tours for Employee Reward & Incentive Trips, Team Outings & Offsites, Annual Company Retreats, Conferences & Business Meetings, Dealer & Distributor Meets, Client Engagement Events, Training & Workshops, and Educational & Industrial Visits. With <strong>transparent pricing, professional service, and end-to-end travel management</strong>, we deliver corporate travel experiences that are efficient, comfortable, and memorable.",
      },
    ],
    features: [
      { title: "Employee Incentive Trips", icon: "Award" },
      { title: "Team Offsites", icon: "Users" },
      { title: "Business Conferences", icon: "Presentation" },
      { title: "Company Retreats", icon: "Building" },
      { title: "Dealer Meets", icon: "Handshake" },
      { title: "Client Events", icon: "Star" },
      { title: "Training Workshops", icon: "BookOpen" },
      { title: "Industrial Visits", icon: "Factory" },
    ],
    included: [
      "Domestic & International Flight Bookings",
      "Hotel & Resort Reservations",
      "Airport Transfers & Local Transport",
      "Tempo Traveller & Luxury Coach Arrangements",
      "Customized Corporate Itineraries",
      "Conference Hall & Meeting Venue Bookings",
      "Meal Planning & Gala Dinners",
      "Team Building Activities & Adventures",
      "Visa & Passport Assistance",
      "Dedicated Tour Coordinator & 24/7 Support",
    ],
    whyChooseUs: [
      { title: "Professional Service", desc: "Corporate-grade travel management.", icon: "Briefcase" },
      { title: "Any Team Size", desc: "From 10 to 500+ participants handled seamlessly.", icon: "Users" },
      { title: "End-to-End Management", desc: "Complete travel, venue & activity coordination.", icon: "ClipboardList" },
      { title: "Customized Planning", desc: "Tailored itineraries for every corporate need.", icon: "Compass" },
      { title: "Transparent Pricing", desc: "Clear quotes with no hidden costs.", icon: "Eye" },
      { title: "24/7 Support", desc: "Round-the-clock assistance for your team.", icon: "Headphones" },
      { title: "Best Venues", desc: "Premium conference halls and resorts.", icon: "Building" },
      { title: "Team Building", desc: "Engaging activities for stronger teams.", icon: "Heart" },
    ],
    gallery: [
      "/images/packages/corporate-tour/ash-gerlach-6fF-Ojxov6o-unsplash.jpg",
      "/images/packages/corporate-tour/duy-pham-Cecb0_8Hx-o-unsplash.jpg",
      "/images/packages/corporate-tour/luca-bravo-_WiRAWxAhtg-unsplash.jpg",
      "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80",
    ],
    destinations: [
      { name: "Bali", image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80" },
      { name: "Dubai", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80" },
      { name: "Thailand", image: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?auto=format&fit=crop&w=600&q=80" },
      { name: "Goa", image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f9?auto=format&fit=crop&w=600&q=80" },
      { name: "Rajasthan", image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=600&q=80" },
      { name: "Kerala", image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=600&q=80" },
      { name: "Himachal", image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=600&q=80" },
      { name: "Singapore", image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=600&q=80" },
    ],
    faqs: [
      { q: "How do you handle corporate group bookings?", a: "We provide dedicated coordinators, bulk booking discounts, and customized itineraries for corporate groups of all sizes." },
      { q: "Can you arrange conference venues?", a: "Yes, we book conference halls, meeting rooms, and event venues with audio-visual equipment and catering." },
      { q: "Do you offer team building activities?", a: "Yes, we organize adventure activities, workshop sessions, and team building exercises tailored to your goals." },
      { q: "Can you handle international corporate tours?", a: "Absolutely! We manage international corporate travel including flights, visas, hotels, and local transportation." },
      { q: "What about incentive and reward trips?", a: "We specialize in designing memorable incentive trips that motivate and reward your top performers." },
      { q: "Is there a minimum group size?", a: "No, we handle groups as small as 5 people and as large as 500+ with equal professionalism." },
      { q: "How do you ensure safety for corporate trips?", a: "We conduct safety briefings, provide travel insurance, and have 24/7 support throughout the trip." },
      { q: "Can you arrange gala dinners?", a: "Yes, we plan and execute gala dinners, theme parties, and special events as part of corporate packages." },
      { q: "What is the booking process?", a: "Share your requirements, team size, and budget. We'll present a detailed proposal within 48 hours." },
      { q: "Do you provide post-trip reports?", a: "Yes, we share detailed feedback reports and expense summaries after every corporate tour." },
    ],
  },
];

export const whyChooseUsGeneral = [
  { title: "Experienced Team", desc: "Years of travel expertise ensuring smooth trips.", icon: "ShieldCheck" },
  { title: "Transparent Pricing", desc: "No hidden charges, clear pricing from the start.", icon: "Eye" },
  { title: "No Hidden Charges", desc: "What you see is what you pay.", icon: "CheckCircle" },
  { title: "24×7 Support", desc: "We're here for you anytime, anywhere.", icon: "Headphones" },
  { title: "Trusted Hotels", desc: "Handpicked accommodations for every budget.", icon: "Hotel" },
  { title: "Best Deals", desc: "Competitive prices without compromising quality.", icon: "Tag" },
  { title: "Personalized Service", desc: "Every trip is designed uniquely for you.", icon: "Heart" },
  { title: "Safe Travel", desc: "Your safety is our top priority.", icon: "Shield" },
];

export function getServiceData(slug) {
  return servicesData.find((s) => s.slug === slug);
}

export const serviceSlugs = servicesData.map((s) => s.slug);
